/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth mode and environment; the SPA shows the test-mode user switcher when authMode is Test (defaultUserId: who acts until a user is chosen). */
        get: operations["GetSystemInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user. */
        get: operations["GetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/{folderId}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documents of a folder (usp_ListDocuments): filter by title (case/accent-insensitive substring), status, sort, page; deleted ones only for their owner and admins. */
        get: operations["ListDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The nested tree of a version (any status) with numbering; ETag = version stamp. */
        get: operations["GetTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A node with its ancestors (path). */
        get: operations["GetNode"];
        put?: never;
        post?: never;
        /** Owner, draft only: deletes a node with its whole subtree and contents (usp_DeleteSubtree; ?rowVersion=base64). */
        delete: operations["DeleteNode"];
        options?: never;
        head?: never;
        /** Owner, draft only: renames a node and/or changes its type (rowVersion required). */
        patch: operations["UpdateNode"];
        trace?: never;
    };
    "/api/versions/{versionId}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner, draft only: adds a node (with empty content) under a parent at a position (default last). */
        post: operations["CreateNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{nodeId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner, draft only: re-parents and/or reorders a node within its version; position = 0-based index (default last). */
        post: operations["MoveNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DocHub Content Schema v1: node and mark types, attributes with ranges and values, units, the font list. */
        get: operations["GetContentSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{nodeId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A node's content: ?format=json (default), html or both; ETag = version stamp + row version. */
        get: operations["GetNodeContent"];
        /** Owner or content editor, draft only: saves content (rowVersion required); returns the canonicalized JSON. Validation errors carry JSON paths. */
        put: operations["SaveNodeContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Contents of several nodes of a version (?nodeIds=1,2,3, at most 200) in the given order, e.g. to render a document; ETag = version stamp + row versions. */
        get: operations["GetVersionContents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/nodes/{logicalNodeId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History of one node across all versions (with the document's signings as context), newest first. */
        get: operations["GetNodeHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document-wide activity (nodes, content, versions, permissions, signatures, comments), newest first; filters are optional. */
        get: operations["GetDocumentHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/entries/{entryId}/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diff of a content entry (old → new): blocks with ops, ready-to-render HTML, word counts. */
        get: operations["GetEntryDiff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/entries/{entryId}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A node's content and header as of a history entry (for viewing and restoring an earlier state). */
        get: operations["GetEntryContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/change-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One call for all section badges: per node change counts, last change, script/after-signing flags and structural changes since a baseline (latestSigned, v:{id}, e:{entryId}, d:{isoDate}), plus removed nodes. */
        get: operations["GetChangeSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/nodes/{logicalNodeId}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track changes: the diff of a node's text since a baseline, each insert/delete/format run attributed to the change (user or script + ticket) that made it. */
        get: operations["GetNodeChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin: raw audit.ChangeLog rows of every table, newest first; from/to required (≤ 31 days), other filters optional. */
        get: operations["ListAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Comment threads of a version (document and/or node comments); includePreviousVersions adds older versions' comments on the same nodes. */
        get: operations["ListComments"];
        put?: never;
        /** Owner, editor or approver: comments on the document or a node of a Draft or Signed version, or replies to a top-level comment. */
        post: operations["CreateComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/comments/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Numbers of (not deleted) comments, replies included, on the document and per node of a version (default: the draft, else the current version). */
        get: operations["GetCommentCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Author: edits a comment (rowVersion required). */
        put: operations["UpdateComment"];
        post?: never;
        /** Author or owner: soft-deletes a comment (?rowVersion=base64); a deleted comment with replies stays as "deleted". */
        delete: operations["DeleteComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner or approver: resolves a top-level comment. */
        post: operations["ResolveComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comments/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner or approver: reopens a resolved top-level comment. */
        post: operations["ReopenComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compares two versions (base=versionId|latestSigned, target=versionId|draft): summary and one merged tree; unchanged branches are left out unless includeUnchanged. */
        get: operations["CompareVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/compare/nodes/{logicalNodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Content diff of one node between two versions (same format as the history diff). */
        get: operations["CompareNode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Runs ledger reconciliation and the module-integrity check over the configured window (default: last 48 h). */
        post: operations["ReconcileLedger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tamper-evidence findings, newest first. */
        get: operations["ListAuditFindings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Active users (admins: includeInactive for all), paged; search = prefix of login, display name or e-mail. */
        get: operations["ListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A user by id (also inactive users, e.g. authors in history). */
        get: operations["GetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/node-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node types ordered by sort order and name, with their usage counts. */
        get: operations["ListNodeTypes"];
        put?: never;
        /** Admin: creates a node type (code unique). */
        post: operations["CreateNodeType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/node-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A node type; usageCount = nodes (any version) using it. */
        get: operations["GetNodeType"];
        /** Admin: updates a node type (optimistic concurrency via rowVersion); isActive = false deactivates it. */
        put: operations["UpdateNodeType"];
        post?: never;
        /** Admin: deletes an unused node type (409 in-use otherwise). */
        delete: operations["DeleteNodeType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content-styles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Styles for the editor's style dropdown, optionally of one kind. */
        get: operations["ListContentStyles"];
        put?: never;
        /** Admin: creates a style (styleId unique; properties validated against the style property schema). */
        post: operations["CreateContentStyle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content-styles/stylesheet.css": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** CSS generated from the catalog (.ds-style-Heading1 { … }), revalidated with ETag. */
        get: operations["GetContentStylesheet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/content-styles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A style; usageCount = contents using it. */
        get: operations["GetContentStyle"];
        /** Admin: updates a style (styleId and kind are fixed; rowVersion required); isActive = false deactivates it. */
        put: operations["UpdateContentStyle"];
        post?: never;
        /** Admin: deletes an unused custom style (?rowVersion=base64); built-in → 409 built-in-style, used → 409 in-use. */
        delete: operations["DeleteContentStyle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The whole folder tree, nested and ordered; documentCount = non-deleted documents directly in the folder. */
        get: operations["GetFolderTree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A folder with its breadcrumb path from the root. */
        get: operations["GetFolder"];
        /** Admin: renames a folder (rowVersion required). */
        put: operations["RenameFolder"];
        post?: never;
        /** Admin: deletes an empty folder (?rowVersion=base64); sub-folders or any documents → 409 in-use. */
        delete: operations["DeleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: creates a folder as the last child of the parent (root when parentFolderId is null). */
        post: operations["CreateFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/folders/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: re-parents and/or reorders a folder; position = 0-based index among the new siblings (default last). */
        post: operations["MoveFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a document (owner = caller) with an empty draft, in one transaction. */
        post: operations["CreateDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document details with its versions and my roles (deleted: owner/admin only, else 404). */
        get: operations["GetDocument"];
        /** Owner: renames the document (document-level title; signatures are not affected). */
        put: operations["RenameDocument"];
        post?: never;
        /** Owner: soft-deletes the document (?rowVersion=base64); versions, draft and signatures stay as they are. */
        delete: operations["DeleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner or admin: moves the document to another folder (admins also deleted documents). */
        post: operations["MoveDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner or admin: restores a deleted document, optionally into another folder. */
        post: operations["RestoreDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Owner: new draft = deep copy of the latest signed version (usp_CopyVersionToDraft). */
        post: operations["CreateDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version header; ETag = version stamp (If-None-Match → 304). */
        get: operations["GetVersion"];
        put?: never;
        post?: never;
        /** Owner: discards the draft (?rowVersion=base64); 409 only-version when there is no signed version. */
        delete: operations["DiscardDraft"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/signatures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Required approvers, signatures (isValid = bound to the current content), pending approvers. */
        get: operations["GetSignatures"];
        put?: never;
        /** Approver: signs the draft with its current content hash; the last required signature finalizes it (vN). */
        post: operations["SignVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions/{versionId}/signatures/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Approver: withdraws my signature from the draft. */
        delete: operations["WithdrawSignature"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The owner and all grants; node grants carry the node title from the draft (else the latest signed version) and whether the node is in the draft. */
        get: operations["GetDocumentPermissions"];
        put?: never;
        /** Owner: grants Editor (optionally of one node and its descendants) or Approver to a user. */
        post: operations["GrantDocumentRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/my-permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My effective rights (for the UI): editableLogicalNodeIds are node grants expanded to descendants in the draft or current version. */
        get: operations["GetMyPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/permissions/{grantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Owner: revokes a grant; revoking an approver withdraws their signature on the draft and re-checks whether it is now fully signed. */
        delete: operations["RevokeDocumentRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditRow: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            changedAt?: string;
            tableName?: string;
            operation?: string;
            /** Format: int32 */
            entityId?: number;
            /** Format: int32 */
            documentId?: null | number;
            /** Format: int32 */
            documentVersionId?: null | number;
            /** Format: uuid */
            logicalNodeId?: null | string;
            oldValues?: null | string;
            newValues?: null | string;
            changedColumns?: null | string;
            /** Format: int32 */
            userId?: null | number;
            source?: string;
            dbLogin?: string;
            appName?: null | string;
            correlationId?: null | string;
            operationContext?: null | string;
            ticket?: null | string;
            reason?: null | string;
        };
        ChangeSummary: {
            since: string;
            nodes: components["schemas"]["NodeChangeSummary"][];
            removed: components["schemas"]["RemovedNode"][];
        };
        CommentCounts: {
            /** Format: int32 */
            versionId: number;
            /** Format: int32 */
            document: number;
            nodes: {
                [key: string]: number;
            };
        };
        CommentView: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            versionId: number;
            versionLabel: null | string;
            /** Format: uuid */
            logicalNodeId: null | string;
            nodeTitle: null | string;
            author: components["schemas"]["UserRef"];
            body: null | string;
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            editedAt: null | string;
            /** Format: date-time */
            resolvedAt: null | string;
            resolvedBy: null | components["schemas"]["UserRef"];
            /** Format: byte */
            rowVersion: string;
            replies: components["schemas"]["CommentView"][];
        };
        CompareNode: {
            /** Format: uuid */
            logicalNodeId: string;
            status: string;
            changes: string[];
            base: null | components["schemas"]["NodeSide"];
            target: null | components["schemas"]["NodeSide"];
            contentStats: null | components["schemas"]["DiffStats"];
            children: components["schemas"]["CompareNode"][];
        };
        CompareSummary: {
            /** Format: int32 */
            added: number;
            /** Format: int32 */
            removed: number;
            /** Format: int32 */
            moved: number;
            /** Format: int32 */
            renamed: number;
            /** Format: int32 */
            typeChanged: number;
            /** Format: int32 */
            contentChanged: number;
            /** Format: int32 */
            unchanged: number;
        };
        Comparison: {
            base: components["schemas"]["VersionRef"];
            target: components["schemas"]["VersionRef"];
            summary: components["schemas"]["CompareSummary"];
            tree: components["schemas"]["CompareNode"][];
        };
        ContentDiff: {
            blocks: components["schemas"]["DiffBlock"][];
            html: string;
            stats: components["schemas"]["DiffStats"];
        };
        /** @enum {unknown} */
        ContentStyleKind: "Paragraph" | "Character" | "Table";
        ContentStyleResponse: {
            /** Format: int32 */
            id: number;
            styleId: string;
            name: string;
            kind: components["schemas"]["ContentStyleKind"];
            basedOnStyleId: null | string;
            properties: components["schemas"]["JsonElement"];
            isBuiltIn: boolean;
            isActive: boolean;
            /** Format: byte */
            rowVersion: string;
            /** Format: int32 */
            usageCount: number;
        };
        CreateComment: {
            /** Format: uuid */
            logicalNodeId?: null | string;
            /** Format: int32 */
            parentCommentId?: null | number;
            body: null | string;
        };
        CreateContentStyle: {
            styleId: null | string;
            kind: null | components["schemas"]["ContentStyleKind"];
            name: null | string;
            basedOnStyleId?: null | string;
            properties?: components["schemas"]["JsonElement"];
        };
        CreatedDocument: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            draftVersionId: number;
        };
        CreateDocument: {
            /** Format: int32 */
            folderId?: number;
            title: null | string;
        };
        CreateFolder: {
            /** Format: int32 */
            parentFolderId?: null | number;
            name: null | string;
        };
        CreateGrant: {
            /** Format: int32 */
            userId?: number;
            role: null | components["schemas"]["DocumentRole"];
            /** Format: uuid */
            logicalNodeId?: null | string;
        };
        CreateNode: {
            /** Format: int32 */
            parentNodeId?: null | number;
            /** Format: int32 */
            nodeTypeId?: number;
            title: null | string;
            /** Format: int32 */
            position?: null | number;
        };
        CreateNodeType: {
            code: null | string;
            name: null | string;
            description?: null | string;
            /** Format: int32 */
            sortOrder?: number;
        };
        DeletedNodes: {
            /** Format: int32 */
            deletedCount: number;
        };
        DiffAuthor: {
            /** Format: int64 */
            entryId: number;
            /** Format: int32 */
            userId: null | number;
            displayName: null | string;
            source: string;
            ticket: null | string;
            /** Format: date-time */
            changedAt: string;
        };
        DiffBlock: {
            type: string;
            status: string;
            changes?: null | string[];
            ops?: null | components["schemas"]["DiffOp"][];
            children?: null | components["schemas"]["DiffBlock"][];
            rows?: null | components["schemas"]["DiffCell"][][];
        };
        DiffCell: {
            status: string;
            ops: components["schemas"]["DiffOp"][];
            blocks: components["schemas"]["DiffBlock"][];
        };
        DiffOp: {
            op: string;
            text: string;
            changes?: null | string[];
            by?: null | components["schemas"]["DiffAuthor"];
            formatBy?: null | components["schemas"]["DiffAuthor"];
        };
        DiffStats: {
            /** Format: int32 */
            inserted: number;
            /** Format: int32 */
            deleted: number;
        };
        DocumentDetails: {
            /** Format: int32 */
            id: number;
            /** Format: byte */
            rowVersion: string;
            /** Format: int32 */
            folderId: number;
            title: string;
            status: string;
            owner: components["schemas"]["UserRef"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            deletedAt: null | string;
            versions: components["schemas"]["VersionHeader"][];
            myRoles: components["schemas"]["MyRoles"];
        };
        DocumentListItem: {
            /** Format: int32 */
            id: number;
            /** Format: byte */
            rowVersion: string;
            /** Format: int32 */
            folderId: number;
            title: string;
            status: string;
            /** Format: int32 */
            latestSignedVersion: null | number;
            hasDraft: boolean;
            signatureProgress: null | components["schemas"]["SignatureProgress"];
            owner: components["schemas"]["UserRef"];
            myRoles: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            modifiedAt: string;
        };
        DocumentPermissions: {
            owner: components["schemas"]["UserRef"];
            grants: components["schemas"]["Grant"][];
        };
        /** @enum {unknown} */
        DocumentRole: "Editor" | "Approver";
        FieldChange: {
            field: string;
            old: null | string;
            new: null | string;
        };
        FindingResponse: {
            /** Format: int64 */
            id: number;
            kind: string;
            tableName: null | string;
            /** Format: int32 */
            entityId: null | number;
            /** Format: int32 */
            documentId: null | number;
            /** Format: int32 */
            documentVersionId: null | number;
            /** Format: int64 */
            ledgerTransactionId: null | number;
            /** Format: date-time */
            transactionCommitTimeUtc: null | string;
            principal: null | string;
            detail: null | string;
            /** Format: date-time */
            detectedAtUtc: string;
            afterSigning: boolean;
        };
        FolderNode: {
            /** Format: int32 */
            id: number;
            name: string;
            /** Format: int32 */
            sortOrder: number;
            /** Format: int32 */
            documentCount: number;
            children: components["schemas"]["FolderNode"][];
        };
        FolderRef: {
            /** Format: int32 */
            id: number;
            name: string;
        };
        FolderResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            parentFolderId: null | number;
            name: string;
            /** Format: int32 */
            sortOrder: number;
            path: components["schemas"]["FolderRef"][];
            /** Format: byte */
            rowVersion: string;
        };
        Grant: {
            /** Format: int32 */
            id: number;
            user: components["schemas"]["UserRef"];
            role: components["schemas"]["DocumentRole"];
            /** Format: uuid */
            logicalNodeId: null | string;
            nodeTitle: null | string;
            nodeInCurrentVersion: null | boolean;
            /** Format: date-time */
            grantedAt: string;
            grantedBy: components["schemas"]["UserRef"];
        };
        HistoricalContent: {
            /** Format: int64 */
            entryId: number;
            /** Format: uuid */
            logicalNodeId: string;
            /** Format: int32 */
            versionId: number;
            /** Format: date-time */
            changedAt: string;
            title: null | string;
            /** Format: int32 */
            nodeTypeId: null | number;
            contentJson: components["schemas"]["JsonElement"];
            contentHtml: string;
        };
        HistoryEntry: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            changedAt: string;
            /** Format: int32 */
            versionId: null | number;
            versionLabel: null | string;
            kind: string;
            /** Format: uuid */
            logicalNodeId: null | string;
            user: null | components["schemas"]["UserRef"];
            source: string;
            dbLogin: null | string;
            ticket: null | string;
            reason: null | string;
            summary: string;
            changes: components["schemas"]["FieldChange"][];
            hasContentDiff: boolean;
            afterSigning: boolean;
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        JsonElement: unknown;
        MeResponse: {
            /** Format: int32 */
            id: number;
            login: string;
            displayName: string;
            email: null | string;
            isAdmin: boolean;
        };
        MoveDocument: {
            /** Format: int32 */
            folderId?: number;
            /** Format: byte */
            rowVersion: null | string;
        };
        MoveFolder: {
            /** Format: int32 */
            newParentFolderId?: null | number;
            /** Format: int32 */
            position?: null | number;
            /** Format: byte */
            rowVersion: null | string;
        };
        MoveNode: {
            /** Format: int32 */
            newParentNodeId?: null | number;
            /** Format: int32 */
            position?: null | number;
            /** Format: byte */
            rowVersion: null | string;
        };
        MyRoles: {
            isOwner: boolean;
            isAdmin: boolean;
            isEditor: boolean;
            isApprover: boolean;
            editorNodeScopes: string[];
            canEditStructure: boolean;
            canEditAllContent: boolean;
            editableLogicalNodeIds: string[];
            canComment: boolean;
            canResolve: boolean;
            canSign: boolean;
            canManage: boolean;
            canMove: boolean;
            canRestore: boolean;
        };
        NodeChangeSummary: {
            /** Format: uuid */
            logicalNodeId: string;
            /** Format: int32 */
            changeCount: number;
            /** Format: date-time */
            lastChangedAt: null | string;
            lastChangedBy: null | components["schemas"]["UserRef"];
            hasScriptChange: boolean;
            hasChangeAfterSigning: boolean;
            structural: components["schemas"]["StructuralChange"][];
        };
        NodeContentView: {
            /** Format: int32 */
            nodeId: number;
            /** Format: uuid */
            logicalNodeId: string;
            /** Format: int32 */
            schemaVersion: number;
            contentJson: null | components["schemas"]["JsonElement"];
            contentHtml: null | string;
            /** Format: date-time */
            modifiedAt: string;
            modifiedBy: components["schemas"]["UserRef"];
            /** Format: byte */
            rowVersion: string;
        };
        NodeRef: {
            /** Format: int32 */
            id: number;
            title: string;
            number: string;
        };
        NodeResponse: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            versionId: number;
            /** Format: int32 */
            documentId: number;
            /** Format: uuid */
            logicalNodeId: string;
            /** Format: int32 */
            parentNodeId: null | number;
            /** Format: int32 */
            nodeTypeId: number;
            title: string;
            number: string;
            hasContent: boolean;
            /** Format: int32 */
            sortOrder: number;
            /** Format: byte */
            rowVersion: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            createdByUserId: number;
            /** Format: date-time */
            modifiedAt: string;
            /** Format: int32 */
            modifiedByUserId: number;
            path: components["schemas"]["NodeRef"][];
        };
        NodeSide: {
            title: string;
            number: string;
            /** Format: int32 */
            nodeTypeId: number;
            nodeType: string;
            /** Format: uuid */
            parentLogicalNodeId: null | string;
        };
        NodeTypeResponse: {
            /** Format: int32 */
            id: number;
            code: string;
            name: string;
            description: null | string;
            /** Format: int32 */
            sortOrder: number;
            isActive: boolean;
            /** Format: byte */
            rowVersion: string;
            /** Format: int32 */
            usageCount: number;
        };
        PagedResultOfAuditRow: {
            items: components["schemas"]["AuditRow"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        PagedResultOfDocumentListItem: {
            items: components["schemas"]["DocumentListItem"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        PagedResultOfFindingResponse: {
            items: components["schemas"]["FindingResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        PagedResultOfHistoryEntry: {
            items: components["schemas"]["HistoryEntry"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        PagedResultOfUserResponse: {
            items: components["schemas"]["UserResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
        };
        ReconciliationRunResponse: {
            /** Format: date-time */
            fromUtc: string;
            /** Format: date-time */
            toUtc: string;
            /** Format: int32 */
            newFindings: number;
            /** Format: int32 */
            moduleProblems: number;
        };
        RemovedNode: {
            /** Format: uuid */
            logicalNodeId: string;
            title: string;
            number: string;
            /** Format: int32 */
            nodeTypeId: number;
            /** Format: uuid */
            formerParentLogicalNodeId: null | string;
            /** Format: int32 */
            formerPosition: number;
            /** Format: int64 */
            lastEntryId: null | number;
        };
        RenameDocument: {
            title: null | string;
            /** Format: byte */
            rowVersion: null | string;
        };
        RenameFolder: {
            name: null | string;
            /** Format: byte */
            rowVersion: null | string;
        };
        RestoreDocument: {
            /** Format: int32 */
            folderId?: null | number;
        };
        SaveContent: {
            contentJson: null | components["schemas"]["JsonElement"];
            /** Format: byte */
            rowVersion: null | string;
        };
        SignatureInfo: {
            user: components["schemas"]["UserRef"];
            /** Format: date-time */
            signedAt: string;
            isValid: boolean;
            comment: null | string;
        };
        SignatureProgress: {
            /** Format: int32 */
            signed: number;
            /** Format: int32 */
            required: number;
        };
        SignatureStatus: {
            requiredApprovers: components["schemas"]["UserRef"][];
            signatures: components["schemas"]["SignatureInfo"][];
            pendingApprovers: components["schemas"]["UserRef"][];
            isComplete: boolean;
        };
        SigningResult: {
            signatures: components["schemas"]["SignatureStatus"];
            version: components["schemas"]["VersionHeader"];
        };
        SignRequest: {
            comment?: null | string;
        };
        StructuralChange: {
            kind: string;
            oldNumber: null | string;
            newNumber: null | string;
            oldTitle: null | string;
            newTitle: null | string;
            /** Format: int32 */
            oldNodeTypeId: null | number;
            /** Format: int32 */
            newNodeTypeId: null | number;
        };
        SystemInfo: {
            authMode: string;
            environment: string;
            version: string;
            /** Format: int32 */
            defaultUserId: null | number;
        };
        TreeNode: {
            /** Format: int32 */
            id: number;
            /** Format: uuid */
            logicalNodeId: string;
            /** Format: int32 */
            nodeTypeId: number;
            title: string;
            number: string;
            hasContent: boolean;
            /** Format: int32 */
            sortOrder: number;
            /** Format: byte */
            rowVersion: string;
            children: components["schemas"]["TreeNode"][];
        };
        UpdateComment: {
            body: null | string;
            /** Format: byte */
            rowVersion: null | string;
        };
        UpdateContentStyle: {
            isActive?: boolean;
            /** Format: byte */
            rowVersion: null | string;
            name: null | string;
            basedOnStyleId?: null | string;
            properties?: components["schemas"]["JsonElement"];
        };
        UpdateNode: {
            title?: null | string;
            /** Format: int32 */
            nodeTypeId?: null | number;
            /** Format: byte */
            rowVersion: null | string;
        };
        UpdateNodeType: {
            isActive?: boolean;
            /** Format: byte */
            rowVersion: null | string;
            code: null | string;
            name: null | string;
            description?: null | string;
            /** Format: int32 */
            sortOrder?: number;
        };
        UserRef: {
            /** Format: int32 */
            id: number;
            displayName: string;
        };
        UserResponse: {
            /** Format: int32 */
            id: number;
            login: string;
            displayName: string;
            email: null | string;
            isAdmin: boolean;
            isActive: boolean;
        };
        VersionHeader: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            documentId: number;
            /** Format: byte */
            rowVersion: string;
            status: components["schemas"]["VersionStatus"];
            /** Format: int32 */
            versionNumber: null | number;
            label: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["UserRef"];
            /** Format: date-time */
            signedAt: null | string;
            signedBy: components["schemas"]["UserRef"][];
            /** Format: int32 */
            basedOnVersionId: null | number;
            isCurrent: boolean;
            modifiedAfterSigning: boolean;
        };
        VersionRef: {
            /** Format: int32 */
            versionId: number;
            label: string;
        };
        /** @enum {unknown} */
        VersionStatus: "Draft" | "Signed" | "Deleted";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetSystemInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfo"];
                };
            };
        };
    };
    GetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    ListDocuments: {
        parameters: {
            query?: {
                Search?: string;
                Status?: string;
                SortBy?: string;
                SortDir?: string;
                IncludeDeleted?: boolean;
                IncludeSubfolders?: boolean;
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path: {
                folderId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfDocumentListItem"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetTree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TreeNode"][];
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
        };
    };
    DeleteNode: {
        parameters: {
            query?: {
                rowVersion?: string;
            };
            header?: never;
            path: {
                nodeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletedNodes"];
                };
            };
        };
    };
    UpdateNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    CreateNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNode"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    MoveNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetContentSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    GetNodeContent: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                nodeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeContentView"];
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SaveNodeContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveContent"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeContentView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetVersionContents: {
        parameters: {
            query?: {
                nodeIds?: string;
                format?: string;
            };
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeContentView"][];
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetNodeHistory: {
        parameters: {
            query?: {
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path: {
                id: number;
                logicalNodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfHistoryEntry"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetDocumentHistory: {
        parameters: {
            query?: {
                versionId?: number;
                from?: string;
                to?: string;
                userId?: number;
                source?: string;
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfHistoryEntry"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetEntryDiff: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDiff"];
                };
            };
        };
    };
    GetEntryContent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoricalContent"];
                };
            };
        };
    };
    GetChangeSummary: {
        parameters: {
            query?: {
                since?: string;
            };
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeSummary"];
                };
            };
        };
    };
    GetNodeChanges: {
        parameters: {
            query?: {
                since?: string;
                until?: string;
            };
            header?: never;
            path: {
                id: number;
                logicalNodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDiff"];
                };
            };
        };
    };
    ListAuditLog: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                table?: string;
                operation?: string;
                source?: string;
                userId?: number;
                dbLogin?: string;
                ticket?: string;
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfAuditRow"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ListComments: {
        parameters: {
            query?: {
                logicalNodeId?: string;
                scope?: string;
                includeResolved?: boolean;
                includePreviousVersions?: boolean;
            };
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"][];
                };
            };
        };
    };
    CreateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComment"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetCommentCounts: {
        parameters: {
            query?: {
                versionId?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentCounts"];
                };
            };
        };
    };
    UpdateComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateComment"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteComment: {
        parameters: {
            query?: {
                rowVersion?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ResolveComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"];
                };
            };
        };
    };
    ReopenComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentView"];
                };
            };
        };
    };
    CompareVersions: {
        parameters: {
            query?: {
                base?: string;
                target?: string;
                includeUnchanged?: boolean;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comparison"];
                };
            };
        };
    };
    CompareNode: {
        parameters: {
            query?: {
                base?: string;
                target?: string;
            };
            header?: never;
            path: {
                id: number;
                logicalNodeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentDiff"];
                };
            };
        };
    };
    ReconcileLedger: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationRunResponse"];
                };
            };
        };
    };
    ListAuditFindings: {
        parameters: {
            query?: {
                Page?: number;
                PageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfFindingResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    ListUsers: {
        parameters: {
            query?: {
                Search?: string;
                Page?: number;
                PageSize?: number;
                IncludeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedResultOfUserResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    ListNodeTypes: {
        parameters: {
            query?: {
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTypeResponse"][];
                };
            };
        };
    };
    CreateNodeType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNodeType"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTypeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetNodeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTypeResponse"];
                };
            };
        };
    };
    UpdateNodeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNodeType"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTypeResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteNodeType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListContentStyles: {
        parameters: {
            query?: {
                kind?: components["schemas"]["ContentStyleKind"];
                includeInactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentStyleResponse"][];
                };
            };
        };
    };
    CreateContentStyle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContentStyle"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentStyleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetContentStylesheet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/css": string;
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetContentStyle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentStyleResponse"];
                };
            };
        };
    };
    UpdateContentStyle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContentStyle"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContentStyleResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteContentStyle: {
        parameters: {
            query?: {
                rowVersion?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetFolderTree: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderNode"][];
                };
            };
        };
    };
    GetFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
        };
    };
    RenameFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameFolder"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteFolder: {
        parameters: {
            query?: {
                rowVersion?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolder"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    MoveFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveFolder"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FolderResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    CreateDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDocument"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedDocument"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetails"];
                };
            };
        };
    };
    RenameDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetails"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    DeleteDocument: {
        parameters: {
            query?: {
                rowVersion?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoveDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetails"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    RestoreDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["RestoreDocument"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetails"];
                };
            };
        };
    };
    CreateDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionHeader"];
                };
            };
        };
    };
    GetVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionHeader"];
                };
            };
            /** @description Not Modified */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DiscardDraft: {
        parameters: {
            query?: {
                rowVersion?: string;
            };
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetSignatures: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignatureStatus"];
                };
            };
        };
    };
    SignVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["SignRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningResult"];
                };
            };
        };
    };
    WithdrawSignature: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                versionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SigningResult"];
                };
            };
        };
    };
    GetDocumentPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentPermissions"];
                };
            };
        };
    };
    GrantDocumentRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrant"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grant"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    GetMyPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MyRoles"];
                };
            };
        };
    };
    RevokeDocumentRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                grantId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
