using System.Data;
using DocHub.Infrastructure.Persistence;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;

namespace DocHub.Infrastructure.Audit;

internal sealed class LedgerReconciliation(DocHubDbContext db, IAuditModuleHashes expected, TimeProvider time) : ILedgerReconciliation
{
    /// <summary>Reconciliation scans the ledger history of the window; it runs nightly, so it may take minutes.</summary>
    private static readonly TimeSpan CommandTimeout = TimeSpan.FromMinutes(30);

    private const string ModulesSql = """
        SELECT OBJECT_SCHEMA_NAME([o].[object_id]) + N'.' + [o].[name] AS [Name], [m].[definition] AS [Definition],
               CAST(COALESCE(OBJECTPROPERTY([o].[object_id], N'ExecIsTriggerDisabled'), 0) AS BIT) AS [Disabled]
        FROM sys.objects AS [o]
        LEFT JOIN sys.sql_modules AS [m] ON [m].[object_id] = [o].[object_id]
        WHERE [o].[type] IN ('P', 'FN', 'IF', 'TF', 'V', 'TR')
          AND (OBJECT_SCHEMA_NAME([o].[object_id]) = N'audit' OR ([o].[type] = 'TR' AND [o].[name] LIKE N'TR[_]%[_]Audit'))
          -- Ledger views (<Table>_Ledger) are generated by SQL Server, not modules of the project.
          AND NOT EXISTS (SELECT 1 FROM sys.views AS [v] WHERE [v].[object_id] = [o].[object_id] AND [v].[ledger_view_type] <> 0);
        """;

    public async Task<ReconciliationRun> RunAsync(DateTime fromUtc, CancellationToken cancellationToken)
    {
        if (db.Database.CurrentTransaction is not null)
        {
            throw new InvalidOperationException("Ledger reconciliation verifies the ledger and must not run inside a transaction.");
        }

        await db.Database.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        try
        {
            var problems = await CheckModulesAsync(cancellationToken).ConfigureAwait(false);
            foreach (var (module, detail) in problems)
            {
                await ExecuteAsync("audit.usp_RecordModuleIntegrityFinding", cancellationToken,
                    new SqlParameter("@Module", SqlDbType.NVarChar, 256) { Value = module },
                    new SqlParameter("@Detail", SqlDbType.NVarChar, 1000) { Value = detail }).ConfigureAwait(false);
            }

            var to = time.GetUtcNow().UtcDateTime;
            var newFindings = new SqlParameter("@NewFindings", SqlDbType.Int) { Direction = ParameterDirection.Output };
            await ExecuteAsync("audit.usp_ReconcileLedger", cancellationToken,
                new SqlParameter("@From", SqlDbType.DateTime2) { Value = fromUtc },
                new SqlParameter("@To", SqlDbType.DateTime2) { Value = to },
                newFindings).ConfigureAwait(false);
            return new ReconciliationRun(fromUtc, to, (int)newFindings.Value, problems.Count);
        }
        finally
        {
            await db.Database.CloseConnectionAsync().ConfigureAwait(false);
        }
    }

    /// <summary>Rule 6: every expected module exists, is readable, enabled (triggers) and matches its generated hash.</summary>
    private async Task<List<(string Module, string Detail)>> CheckModulesAsync(CancellationToken cancellationToken)
    {
        var actual = new Dictionary<string, (string? Definition, bool Disabled)>(StringComparer.OrdinalIgnoreCase);
        await using (var command = CreateCommand(ModulesSql, CommandType.Text))
        await using (var reader = await command.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false))
        {
            while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false))
            {
                actual[reader.GetString(0)] = (await reader.IsDBNullAsync(1, cancellationToken).ConfigureAwait(false) ? null : reader.GetString(1), reader.GetBoolean(2));
            }
        }

        var problems = new List<(string, string)>();
        foreach (var (module, hash) in expected.Hashes.OrderBy(m => m.Key, StringComparer.Ordinal))
        {
            if (!actual.TryGetValue(module, out var found))
            {
                problems.Add((module, "Module is missing."));
            }
            else if (found.Definition is null)
            {
                problems.Add((module, "Definition can't be read (missing VIEW DEFINITION or WITH ENCRYPTION)."));
            }
            else if (ModuleDefinition.Hash(found.Definition) is var actualHash && !string.Equals(actualHash, hash, StringComparison.OrdinalIgnoreCase))
            {
                problems.Add((module, $"Definition hash {actualHash} differs from the DB project's {hash}."));
            }
            else if (found.Disabled)
            {
                problems.Add((module, "Trigger is disabled."));
            }
        }

        // Audit modules that the DB project doesn't define (e.g. a procedure added by hand into the audit schema).
        foreach (var module in actual.Keys.Where(m => !expected.Hashes.ContainsKey(m)).Order(StringComparer.Ordinal))
        {
            problems.Add((module, "Module is not part of the DB project."));
        }

        return problems;
    }

    private async Task ExecuteAsync(string procedure, CancellationToken cancellationToken, params SqlParameter[] parameters)
    {
        await using var command = CreateCommand(procedure, CommandType.StoredProcedure);
        command.Parameters.AddRange(parameters);

        // Ledger verification returns result sets; only the output parameter matters.
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    private SqlCommand CreateCommand(string text, CommandType type)
    {
#pragma warning disable CA2100 // Fixed procedure names and SQL text.
        var command = (SqlCommand)db.Database.GetDbConnection().CreateCommand();
#pragma warning restore CA2100
        command.CommandText = text;
        command.CommandType = type;
        command.CommandTimeout = (int)CommandTimeout.TotalSeconds;
        return command;
    }
}
