-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
/*
Ledger reconciliation (T21 §4). Compares the ledger history of the audited tables with audit.ChangeLog, using the change
rules of the audit triggers, and records findings (rules 1–5; rule 6, module integrity, is checked by the API):
  1 TriggerBypass    a ledger change the triggers would have audited, without a ChangeLog row of the same transaction;
  2 ForgedAuditRow   a ChangeLog row its ledger transaction doesn't back (entity not changed, Source/DbLogin not matching
                     the transaction principal);
  3 StampTampering   a VersionStamp change not caused by an audited change of the version (or clearing TamperedAt);
  4 LedgerIntegrity  sp_verify_database_ledger(_from_digest_storage) failed;
  5 SchemaTampering  a ledger table/column dropped, renamed or transferred, or created outside the allow-list (all time).
Transactions older than the first ReconciliationBaseline row are ignored (rules 1–3). A finding is recorded once; for each
affected version the procedure writes a ChangeLog row (OperationContext 'Reconciliation') and advances VersionStamp, sets
TamperedAt of a Signed version when the finding's transaction committed at or after the version's ledger signing
transaction, and marks bypassed NodeContent rows DerivedStale.
EXECUTE AS OWNER: the procedure reads objects by object id through dynamic SQL (renamed/transferred/dropped baseline and
finding tables), which ownership chaining doesn't cover. Ledger transactions still record the caller's login.
Must not run inside a transaction (ledger verification refuses user transactions). @Digest: a digest from
sys.sp_generate_database_ledger_digest, used when no automatic digest storage is configured (local, tests). @To NULL =
every transaction committed from @From on.
*/
CREATE PROCEDURE [audit].[usp_ReconcileLedger]
    @From        DATETIME2 (7),
    @To          DATETIME2 (7)  = NULL,
    @Digest      NVARCHAR (MAX) = NULL,
    @NewFindings INT            = NULL OUTPUT
WITH EXECUTE AS OWNER
AS
BEGIN
    SET NOCOUNT ON;
    SET XACT_ABORT ON;

    IF @@TRANCOUNT > 0
        THROW 50101, N'Ledger reconciliation must not run inside a transaction.', 1;

    IF @From IS NULL
        THROW 50102, N'@From is required.', 1;

    CREATE TABLE [#Finding]
    (
        [Key]                 INT IDENTITY (1, 1) PRIMARY KEY,
        [Kind]                VARCHAR (40) COLLATE DATABASE_DEFAULT NOT NULL,
        [TableName]           NVARCHAR (256) COLLATE DATABASE_DEFAULT NULL,
        [EntityId]            INT             NULL,
        [DocumentId]          INT             NULL,
        [DocumentVersionId]   INT             NULL,
        [LedgerTransactionId] BIGINT          NULL,
        [Detail]              NVARCHAR (1000) COLLATE DATABASE_DEFAULT NULL,
        [MarksDerivedStale]   BIT             NOT NULL DEFAULT (0)
    );

    -- Rule 4 — ledger integrity, first and outside any transaction.
    DECLARE @IntegrityError NVARCHAR (1000);
    DECLARE @Locations NVARCHAR (MAX) = (SELECT * FROM sys.database_ledger_digest_locations FOR JSON AUTO, INCLUDE_NULL_VALUES);
    BEGIN TRY
        IF @Locations IS NOT NULL
            EXEC sys.sp_verify_database_ledger_from_digest_storage @Locations;
        ELSE IF @Digest IS NOT NULL
            EXEC sys.sp_verify_database_ledger @Digest;
    END TRY
    BEGIN CATCH
        SET @IntegrityError = LEFT(CONCAT(N'Msg ', ERROR_NUMBER(), N': ', ERROR_MESSAGE()), 1000);
    END CATCH;

    IF @IntegrityError IS NOT NULL
        INSERT INTO [#Finding] ([Kind], [Detail]) VALUES ('LedgerIntegrity', @IntegrityError);

    -- §2 — every object that ever was audit.ReconciliationBaseline ('B') / audit.ReconciliationFinding ('F'), by object id.
    CREATE TABLE [#Object] ([Role] CHAR (1) COLLATE DATABASE_DEFAULT NOT NULL, [ObjectId] INT NOT NULL, [QualifiedName] NVARCHAR (300) COLLATE DATABASE_DEFAULT NOT NULL);
    INSERT INTO [#Object] ([Role], [ObjectId], [QualifiedName])
    SELECT DISTINCT [r].[Role], [o].[object_id], QUOTENAME(OBJECT_SCHEMA_NAME([o].[object_id])) + N'.' + QUOTENAME([o].[name])
    FROM (VALUES ('B', N'ReconciliationBaseline'), ('F', N'ReconciliationFinding')) AS [r] ([Role], [Name])
    CROSS APPLY (SELECT [h].[object_id] FROM sys.ledger_table_history AS [h] WHERE [h].[schema_name] COLLATE DATABASE_DEFAULT = N'audit' AND [h].[table_name] COLLATE DATABASE_DEFAULT = [r].[Name]
                 UNION
                 SELECT OBJECT_ID(N'[audit].' + QUOTENAME([r].[Name]))) AS [x] ([ObjectId])
    JOIN sys.tables AS [o] ON [o].[object_id] = [x].[ObjectId];

    -- Findings of reconciliation, of every such object (their ChangeLog rows are not forged, rule 2).
    CREATE TABLE [#FindingTx] ([Id] BIGINT NOT NULL, [TransactionId] BIGINT NOT NULL);

    DECLARE @Baseline BIGINT, @Value BIGINT, @Role CHAR (1), @Name NVARCHAR (300), @Current BIT, @Sql NVARCHAR (MAX);
    DECLARE [objects] CURSOR LOCAL FAST_FORWARD FOR
        SELECT [Role], [QualifiedName], CASE WHEN [ObjectId] = OBJECT_ID(N'[audit].[ReconciliationFinding]') THEN 1 ELSE 0 END FROM [#Object];
    OPEN [objects];
    FETCH NEXT FROM [objects] INTO @Role, @Name, @Current;
    WHILE @@FETCH_STATUS = 0
    BEGIN
        -- An object without the expected columns isn't one of ours any more; rule 5 reports what happened to it.
        BEGIN TRY
            IF @Role = 'B'
            BEGIN
                SET @Sql = N'SELECT @Value = MIN([ledger_start_transaction_id]) FROM ' + @Name + N';';
                EXEC sys.sp_executesql @Sql, N'@Value BIGINT OUTPUT', @Value = @Value OUTPUT;
                IF @Value IS NOT NULL AND (@Baseline IS NULL OR @Value < @Baseline)
                    SET @Baseline = @Value;
            END
            ELSE
            BEGIN
                SET @Sql = N'SELECT [Id], [ledger_start_transaction_id] FROM ' + @Name + N';';
                INSERT INTO [#FindingTx] ([Id], [TransactionId]) EXEC sys.sp_executesql @Sql;
                IF @Current = 0
                BEGIN
                    -- Re-import findings of a dropped/renamed/transferred findings table, so they can't be made to vanish.
                    SET @Sql = N'
                    INSERT INTO [audit].[ReconciliationFinding] ([Kind], [TableName], [EntityId], [DocumentId], [DocumentVersionId], [LedgerTransactionId],
                                                                 [TransactionCommitTime], [Principal], [Detail], [DetectedAt], [AfterSigning])
                    SELECT [o].[Kind], [o].[TableName], [o].[EntityId], [o].[DocumentId], [o].[DocumentVersionId], [o].[LedgerTransactionId],
                           [o].[TransactionCommitTime], [o].[Principal], [o].[Detail], [o].[DetectedAt], [o].[AfterSigning]
                    FROM ' + @Name + N' AS [o]
                    WHERE NOT EXISTS (SELECT 1 FROM [audit].[ReconciliationFinding] AS [f]
                                      WHERE [f].[Kind] = [o].[Kind] AND [f].[TableName] IS NOT DISTINCT FROM [o].[TableName]
                                        AND [f].[EntityId] IS NOT DISTINCT FROM [o].[EntityId]
                                        AND [f].[LedgerTransactionId] IS NOT DISTINCT FROM [o].[LedgerTransactionId]
                                        AND ([f].[LedgerTransactionId] IS NOT NULL OR [f].[Detail] IS NOT DISTINCT FROM [o].[Detail]));';
                    EXEC sys.sp_executesql @Sql;
                END;
            END;
        END TRY
        BEGIN CATCH
        END CATCH;

        FETCH NEXT FROM [objects] INTO @Role, @Name, @Current;
    END;
    CLOSE [objects];
    DEALLOCATE [objects];

    -- Ledger transactions of the window, from the baseline on, with their principal. The principal is a login (or external
    -- principal) name; membership is resolved by SID, by user name when the SID can't be resolved.
    CREATE TABLE [#Tx]
    (
        [TransactionId] BIGINT         NOT NULL PRIMARY KEY,
        [CommitTime]    DATETIME2 (7)  NOT NULL,
        [Principal]     NVARCHAR (128) COLLATE DATABASE_DEFAULT NOT NULL,
        [IsApi]         BIT            NOT NULL
    );
    INSERT INTO [#Tx] ([TransactionId], [CommitTime], [Principal], [IsApi])
    SELECT [t].[transaction_id], [t].[commit_time], [t].[principal_name] COLLATE DATABASE_DEFAULT,
           CASE WHEN EXISTS (SELECT 1
                             FROM sys.database_role_members AS [m]
                             JOIN sys.database_principals AS [p] ON [p].[principal_id] = [m].[member_principal_id]
                             WHERE [m].[role_principal_id] = DATABASE_PRINCIPAL_ID(N'app_api')
                               AND ([p].[sid] = SUSER_SID([t].[principal_name])
                                    OR (SUSER_SID([t].[principal_name]) IS NULL AND [p].[name] = [t].[principal_name])))
                THEN 1 ELSE 0 END
    FROM sys.database_ledger_transactions AS [t]
    -- No upper bound unless @To is given: commit_time can run ahead of SYSUTCDATETIME() by milliseconds, so "until now"
    -- must not exclude just-committed transactions.
    WHERE [t].[commit_time] >= @From AND (@To IS NULL OR [t].[commit_time] <= @To)
      AND [t].[transaction_id] >= COALESCE(@Baseline, 0);

    -- Every ledger change of an audited table in the window: the INSERT (after) and DELETE (before) images of one key in
    -- one transaction are paired in sequence order. Audited = what the trigger rules log: insert, delete, an audited column
    -- changed (strings as VARBINARY), or a derived NodeContent column changed by a principal that isn't the API.
    CREATE TABLE [#Change]
    (
        [TableName]     NVARCHAR (128) COLLATE DATABASE_DEFAULT NOT NULL,
        [EntityId]      INT            NOT NULL,
        [TransactionId] BIGINT         NOT NULL,
        [DocumentId]    INT            NULL,
        [VersionNew]    INT            NULL,
        [VersionOld]    INT            NULL,
        [Audited]       BIT            NOT NULL
    );
    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[User_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.User', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           NULL,
           NULL, NULL,
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR CAST([i].[Login] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Login] AS VARBINARY (MAX))
                     OR CAST([i].[DisplayName] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[DisplayName] AS VARBINARY (MAX))
                     OR CAST([i].[Email] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Email] AS VARBINARY (MAX))
                     OR [i].[IsAdmin] IS DISTINCT FROM [d].[IsAdmin]
                     OR [i].[IsActive] IS DISTINCT FROM [d].[IsActive]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[Folder_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.Folder', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           NULL,
           NULL, NULL,
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR [i].[ParentFolderId] IS DISTINCT FROM [d].[ParentFolderId]
                     OR CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX))
                     OR [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder]
                     OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
                     OR [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[NodeType_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.NodeType', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           NULL,
           NULL, NULL,
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR CAST([i].[Code] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Code] AS VARBINARY (MAX))
                     OR CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX))
                     OR CAST([i].[Description] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Description] AS VARBINARY (MAX))
                     OR [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder]
                     OR [i].[IsActive] IS DISTINCT FROM [d].[IsActive]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[ContentStyle_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.ContentStyle', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           NULL,
           NULL, NULL,
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR CAST([i].[StyleId] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[StyleId] AS VARBINARY (MAX))
                     OR CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX))
                     OR [i].[Kind] IS DISTINCT FROM [d].[Kind]
                     OR CAST([i].[BasedOnStyleId] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[BasedOnStyleId] AS VARBINARY (MAX))
                     OR CAST([i].[PropertiesJson] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[PropertiesJson] AS VARBINARY (MAX))
                     OR [i].[IsBuiltIn] IS DISTINCT FROM [d].[IsBuiltIn]
                     OR [i].[IsActive] IS DISTINCT FROM [d].[IsActive]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[Document_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.Document', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           COALESCE([i].[Id], [d].[Id]),
           NULL, NULL,
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR [i].[FolderId] IS DISTINCT FROM [d].[FolderId]
                     OR CAST([i].[Title] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Title] AS VARBINARY (MAX))
                     OR [i].[OwnerUserId] IS DISTINCT FROM [d].[OwnerUserId]
                     OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
                     OR [i].[DeletedAt] IS DISTINCT FROM [d].[DeletedAt]
                     OR [i].[DeletedByUserId] IS DISTINCT FROM [d].[DeletedByUserId]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[DocumentVersion_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.DocumentVersion', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           COALESCE([i].[DocumentId], [d].[DocumentId]),
           [i].[Id], [d].[Id],
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]
                     OR [i].[Status] IS DISTINCT FROM [d].[Status]
                     OR [i].[VersionNumber] IS DISTINCT FROM [d].[VersionNumber]
                     OR [i].[BasedOnVersionId] IS DISTINCT FROM [d].[BasedOnVersionId]
                     OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
                     OR [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId]
                     OR [i].[SignedAt] IS DISTINCT FROM [d].[SignedAt]
                     OR [i].[SignedContentHash] IS DISTINCT FROM [d].[SignedContentHash]
                     OR [i].[IsCurrent] IS DISTINCT FROM [d].[IsCurrent]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[VersionSignature_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.VersionSignature', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           (SELECT [v].[DocumentId] FROM [app].[DocumentVersion] AS [v] WHERE [v].[Id] = COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId])),
           [i].[DocumentVersionId], [d].[DocumentVersionId],
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
                     OR [i].[UserId] IS DISTINCT FROM [d].[UserId]
                     OR [i].[SignedAt] IS DISTINCT FROM [d].[SignedAt]
                     OR [i].[ContentHash] IS DISTINCT FROM [d].[ContentHash]
                     OR [i].[WithdrawnAt] IS DISTINCT FROM [d].[WithdrawnAt]
                     OR CAST([i].[Comment] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Comment] AS VARBINARY (MAX))
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[DocumentNode_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.DocumentNode', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           (SELECT [v].[DocumentId] FROM [app].[DocumentVersion] AS [v] WHERE [v].[Id] = COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId])),
           [i].[DocumentVersionId], [d].[DocumentVersionId],
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
                     OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
                     OR [i].[ParentNodeId] IS DISTINCT FROM [d].[ParentNodeId]
                     OR [i].[NodeTypeId] IS DISTINCT FROM [d].[NodeTypeId]
                     OR CAST([i].[Title] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Title] AS VARBINARY (MAX))
                     OR [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder]
                     OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
                     OR [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId]
                     OR [i].[ModifiedAt] IS DISTINCT FROM [d].[ModifiedAt]
                     OR [i].[ModifiedByUserId] IS DISTINCT FROM [d].[ModifiedByUserId]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[NodeId], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[NodeContent_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.NodeContent', COALESCE([i].[NodeId], [d].[NodeId]), [t].[TransactionId],
           (SELECT [v].[DocumentId] FROM [app].[DocumentVersion] AS [v] WHERE [v].[Id] = COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId])),
           [i].[DocumentVersionId], [d].[DocumentVersionId],
           CASE WHEN [i].[NodeId] IS NULL OR [d].[NodeId] IS NULL
         OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
                     OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
                     OR [i].[SchemaVersion] IS DISTINCT FROM [d].[SchemaVersion]
                     OR CAST([i].[ContentJson] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[ContentJson] AS VARBINARY (MAX))
                     OR [i].[ModifiedAt] IS DISTINCT FROM [d].[ModifiedAt]
                     OR [i].[ModifiedByUserId] IS DISTINCT FROM [d].[ModifiedByUserId]
                     OR ([t].[IsApi] = 0 AND (CAST([i].[ContentHtml] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[ContentHtml] AS VARBINARY (MAX)) OR CAST([i].[PlainText] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[PlainText] AS VARBINARY (MAX)) OR [i].[ContentHash] IS DISTINCT FROM [d].[ContentHash]))
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[NodeId] = [i].[NodeId] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[DocumentPermission_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.DocumentPermission', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           COALESCE([i].[DocumentId], [d].[DocumentId]),
           NULL, NULL,
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]
                     OR [i].[UserId] IS DISTINCT FROM [d].[UserId]
                     OR [i].[Role] IS DISTINCT FROM [d].[Role]
                     OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
                     OR [i].[GrantedAt] IS DISTINCT FROM [d].[GrantedAt]
                     OR [i].[GrantedByUserId] IS DISTINCT FROM [d].[GrantedByUserId]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[Id], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[Comment_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Change] ([TableName], [EntityId], [TransactionId], [DocumentId], [VersionNew], [VersionOld], [Audited])
    SELECT N'app.Comment', COALESCE([i].[Id], [d].[Id]), [t].[TransactionId],
           COALESCE([i].[DocumentId], [d].[DocumentId]),
           NULL, NULL,
           CASE WHEN [i].[Id] IS NULL OR [d].[Id] IS NULL
         OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]
                     OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
                     OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
                     OR [i].[ParentCommentId] IS DISTINCT FROM [d].[ParentCommentId]
                     OR [i].[AuthorUserId] IS DISTINCT FROM [d].[AuthorUserId]
                     OR CAST([i].[Body] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Body] AS VARBINARY (MAX))
                     OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
                     OR [i].[EditedAt] IS DISTINCT FROM [d].[EditedAt]
                     OR [i].[DeletedAt] IS DISTINCT FROM [d].[DeletedAt]
                     OR [i].[ResolvedAt] IS DISTINCT FROM [d].[ResolvedAt]
                     OR [i].[ResolvedByUserId] IS DISTINCT FROM [d].[ResolvedByUserId]
                THEN 1 ELSE 0 END
    FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
    FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
        ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[Id] = [i].[Id] AND [d].[n] = [i].[n]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]);

    -- ChangeLog rows written in the window (hidden ledger column: written by SQL Server, immutable).
    CREATE TABLE [#Log]
    (
        [Id]                BIGINT         NOT NULL,
        [TransactionId]     BIGINT         NOT NULL,
        [TableName]         NVARCHAR (128) COLLATE DATABASE_DEFAULT NOT NULL,
        [Operation]         CHAR (1) COLLATE DATABASE_DEFAULT NOT NULL,
        [EntityId]          INT            NOT NULL,
        [DocumentId]        INT            NULL,
        [DocumentVersionId] INT            NULL,
        [OldVersionId]      INT            NULL,
        [Source]            VARCHAR (10) COLLATE DATABASE_DEFAULT NOT NULL,
        [DbLogin]           NVARCHAR (128) COLLATE DATABASE_DEFAULT NOT NULL
    );
    INSERT INTO [#Log] ([Id], [TransactionId], [TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [OldVersionId], [Source], [DbLogin])
    SELECT [cl].[Id], [cl].[ledger_start_transaction_id], [cl].[TableName], [cl].[Operation], [cl].[EntityId], [cl].[DocumentId], [cl].[DocumentVersionId],
           TRY_CONVERT(INT, JSON_VALUE([cl].[OldValues], N'$.DocumentVersionId')), [cl].[Source], [cl].[DbLogin]
    FROM [audit].[ChangeLog] AS [cl]
    JOIN [#Tx] AS [t] ON [t].[TransactionId] = [cl].[ledger_start_transaction_id];

    -- Rule 1 — trigger bypass.
    INSERT INTO [#Finding] ([Kind], [TableName], [EntityId], [DocumentId], [DocumentVersionId], [LedgerTransactionId], [Detail], [MarksDerivedStale])
    SELECT 'TriggerBypass', [c].[TableName], [c].[EntityId], MAX([c].[DocumentId]), MAX(COALESCE([c].[VersionNew], [c].[VersionOld])), [c].[TransactionId],
           N'Ledger change without an audit row of the same transaction (trigger disabled or bypassed).',
           CASE WHEN [c].[TableName] = N'app.NodeContent' THEN 1 ELSE 0 END
    FROM [#Change] AS [c]
    WHERE [c].[Audited] = 1
      AND NOT EXISTS (SELECT 1 FROM [#Log] AS [cl]
                      WHERE [cl].[TransactionId] = [c].[TransactionId] AND [cl].[TableName] = [c].[TableName] AND [cl].[EntityId] = [c].[EntityId])
    GROUP BY [c].[TableName], [c].[EntityId], [c].[TransactionId];

    -- Rule 2 — forged audit rows.
    INSERT INTO [#Finding] ([Kind], [TableName], [EntityId], [DocumentId], [DocumentVersionId], [LedgerTransactionId], [Detail])
    SELECT 'ForgedAuditRow', [g].[TableName], [g].[EntityId], MAX([g].[DocumentId]), MAX([g].[DocumentVersionId]), [g].[TransactionId],
           LEFT(STRING_AGG(CONCAT(N'ChangeLog ', [g].[Id], N': ', [g].[Reason]), N'; '), 1000)
    FROM (SELECT [cl].[Id], [cl].[TableName], [cl].[EntityId], [cl].[DocumentId], [cl].[TransactionId],
                 CASE WHEN [cl].[TableName] IN (N'app.DocumentVersion', N'app.VersionSignature', N'app.DocumentNode', N'app.NodeContent')
                      THEN [cl].[DocumentVersionId] END AS [DocumentVersionId],
                 CASE
                     WHEN [cl].[TableName] = N'audit.ReconciliationFinding' THEN
                         CASE WHEN [cl].[Operation] = 'I'
                                   AND EXISTS (SELECT 1 FROM [#FindingTx] AS [f] WHERE [f].[Id] = [cl].[EntityId] AND [f].[TransactionId] = [cl].[TransactionId])
                              THEN NULL
                              ELSE N'reconciliation row without a finding inserted in the same transaction' END
                     WHEN [cl].[TableName] NOT IN (N'app.User', N'app.Folder', N'app.NodeType', N'app.ContentStyle', N'app.Document', N'app.DocumentVersion', N'app.VersionSignature', N'app.DocumentNode', N'app.NodeContent', N'app.DocumentPermission', N'app.Comment') THEN N'not an audited table'
                     WHEN NOT EXISTS (SELECT 1 FROM [#Change] AS [c]
                                      WHERE [c].[TableName] = [cl].[TableName] AND [c].[EntityId] = [cl].[EntityId] AND [c].[TransactionId] = [cl].[TransactionId])
                         THEN N'its ledger transaction did not change the entity'
                     WHEN [cl].[Source] = 'App' AND [t].[IsApi] = 0
                         THEN CONCAT(N'Source = App, but the transaction principal ', [t].[Principal], N' is not an app_api member')
                     WHEN [cl].[Source] = 'Script' AND NOT ([cl].[DbLogin] = [t].[Principal] OR SUSER_SID([cl].[DbLogin]) = SUSER_SID([t].[Principal]))
                         THEN CONCAT(N'DbLogin ', [cl].[DbLogin], N' is not the transaction principal ', [t].[Principal])
                 END AS [Reason]
          FROM [#Log] AS [cl]
          JOIN [#Tx] AS [t] ON [t].[TransactionId] = [cl].[TransactionId]) AS [g]
    WHERE [g].[Reason] IS NOT NULL
    GROUP BY [g].[TableName], [g].[EntityId], [g].[TransactionId];

    -- Rule 3 — stamp tampering: a VersionStamp change is legitimate only together with an audited change of the version in
    -- the same transaction (the triggers' MERGE, or reconciliation's own ChangeLog row), never clearing or moving TamperedAt
    -- and never moving LastChangeLogId back. Identical before/after images (no-op updates) are ignored.
    WITH [l] AS (
        SELECT [x].*, ROW_NUMBER() OVER (PARTITION BY [x].[ledger_transaction_id], [x].[DocumentVersionId], [x].[ledger_operation_type] ORDER BY [x].[ledger_sequence_number]) AS [n]
        FROM [app].[VersionStamp_Ledger] AS [x]
        JOIN [#Tx] AS [tx] ON [tx].[TransactionId] = [x].[ledger_transaction_id])
    INSERT INTO [#Finding] ([Kind], [TableName], [EntityId], [DocumentId], [DocumentVersionId], [LedgerTransactionId], [Detail])
    SELECT 'StampTampering', N'app.VersionStamp', [s].[VersionId], MAX([v].[DocumentId]), [s].[VersionId], [s].[TransactionId],
           N'VersionStamp changed without an audited change of the version, or TamperedAt cleared/moved.'
    FROM (SELECT COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId]) AS [VersionId],
                 COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id]) AS [TransactionId],
                 CASE WHEN ([i].[DocumentVersionId] IS NULL OR [d].[DocumentVersionId] IS NULL
                            OR (([d].[TamperedAt] IS NULL OR [i].[TamperedAt] = [d].[TamperedAt]) AND [i].[LastChangeLogId] >= [d].[LastChangeLogId]))
                           AND EXISTS (SELECT 1 FROM [#Log] AS [cl]
                                       WHERE [cl].[TransactionId] = COALESCE([i].[ledger_transaction_id], [d].[ledger_transaction_id])
                                         AND COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId]) IN ([cl].[DocumentVersionId], [cl].[OldVersionId]))
                      THEN 1 ELSE 0 END AS [Legitimate],
                 CASE WHEN [i].[DocumentVersionId] IS NOT NULL AND [d].[DocumentVersionId] IS NOT NULL
                           AND [i].[LastChangeLogId] = [d].[LastChangeLogId] AND [i].[TamperedAt] IS NOT DISTINCT FROM [d].[TamperedAt]
                      THEN 1 ELSE 0 END AS [NoOp]
          FROM (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 1) AS [i]
          FULL OUTER JOIN (SELECT * FROM [l] WHERE [l].[ledger_operation_type] = 2) AS [d]
              ON [d].[ledger_transaction_id] = [i].[ledger_transaction_id] AND [d].[DocumentVersionId] = [i].[DocumentVersionId] AND [d].[n] = [i].[n]) AS [s]
    LEFT JOIN [app].[DocumentVersion] AS [v] ON [v].[Id] = [s].[VersionId]
    WHERE [s].[Legitimate] = 0 AND [s].[NoOp] = 0
    GROUP BY [s].[VersionId], [s].[TransactionId];

    -- Rule 5 — ledger schema tampering, over all time, by object id. The allow-list is the ledger tables and columns of the
    -- DACPAC model (generated from the table scripts).
    CREATE TABLE [#Allowed] ([SchemaName] SYSNAME COLLATE DATABASE_DEFAULT NOT NULL, [TableName] SYSNAME COLLATE DATABASE_DEFAULT NOT NULL, [ColumnName] SYSNAME COLLATE DATABASE_DEFAULT NOT NULL);
    INSERT INTO [#Allowed] ([SchemaName], [TableName], [ColumnName])
    VALUES
        (N'app', N'Comment', N'Id'),
        (N'app', N'Comment', N'DocumentId'),
        (N'app', N'Comment', N'DocumentVersionId'),
        (N'app', N'Comment', N'LogicalNodeId'),
        (N'app', N'Comment', N'ParentCommentId'),
        (N'app', N'Comment', N'AuthorUserId'),
        (N'app', N'Comment', N'Body'),
        (N'app', N'Comment', N'CreatedAt'),
        (N'app', N'Comment', N'EditedAt'),
        (N'app', N'Comment', N'DeletedAt'),
        (N'app', N'Comment', N'ResolvedAt'),
        (N'app', N'Comment', N'ResolvedByUserId'),
        (N'app', N'Comment', N'RowVersion'),
        (N'app', N'Comment', N'ValidFrom'),
        (N'app', N'Comment', N'ValidTo'),
        (N'app', N'Comment', N'ledger_start_transaction_id'),
        (N'app', N'Comment', N'ledger_start_sequence_number'),
        (N'app', N'Comment', N'ledger_end_transaction_id'),
        (N'app', N'Comment', N'ledger_end_sequence_number'),
        (N'app', N'ContentStyle', N'Id'),
        (N'app', N'ContentStyle', N'StyleId'),
        (N'app', N'ContentStyle', N'Name'),
        (N'app', N'ContentStyle', N'Kind'),
        (N'app', N'ContentStyle', N'BasedOnStyleId'),
        (N'app', N'ContentStyle', N'PropertiesJson'),
        (N'app', N'ContentStyle', N'IsBuiltIn'),
        (N'app', N'ContentStyle', N'IsActive'),
        (N'app', N'ContentStyle', N'RowVersion'),
        (N'app', N'ContentStyle', N'ValidFrom'),
        (N'app', N'ContentStyle', N'ValidTo'),
        (N'app', N'ContentStyle', N'ledger_start_transaction_id'),
        (N'app', N'ContentStyle', N'ledger_start_sequence_number'),
        (N'app', N'ContentStyle', N'ledger_end_transaction_id'),
        (N'app', N'ContentStyle', N'ledger_end_sequence_number'),
        (N'app', N'Document', N'Id'),
        (N'app', N'Document', N'FolderId'),
        (N'app', N'Document', N'Title'),
        (N'app', N'Document', N'OwnerUserId'),
        (N'app', N'Document', N'CreatedAt'),
        (N'app', N'Document', N'DeletedAt'),
        (N'app', N'Document', N'DeletedByUserId'),
        (N'app', N'Document', N'RowVersion'),
        (N'app', N'Document', N'ValidFrom'),
        (N'app', N'Document', N'ValidTo'),
        (N'app', N'Document', N'ledger_start_transaction_id'),
        (N'app', N'Document', N'ledger_start_sequence_number'),
        (N'app', N'Document', N'ledger_end_transaction_id'),
        (N'app', N'Document', N'ledger_end_sequence_number'),
        (N'app', N'DocumentNode', N'Id'),
        (N'app', N'DocumentNode', N'DocumentVersionId'),
        (N'app', N'DocumentNode', N'LogicalNodeId'),
        (N'app', N'DocumentNode', N'ParentNodeId'),
        (N'app', N'DocumentNode', N'NodeTypeId'),
        (N'app', N'DocumentNode', N'Title'),
        (N'app', N'DocumentNode', N'SortOrder'),
        (N'app', N'DocumentNode', N'CreatedAt'),
        (N'app', N'DocumentNode', N'CreatedByUserId'),
        (N'app', N'DocumentNode', N'ModifiedAt'),
        (N'app', N'DocumentNode', N'ModifiedByUserId'),
        (N'app', N'DocumentNode', N'RowVersion'),
        (N'app', N'DocumentNode', N'ValidFrom'),
        (N'app', N'DocumentNode', N'ValidTo'),
        (N'app', N'DocumentNode', N'ledger_start_transaction_id'),
        (N'app', N'DocumentNode', N'ledger_start_sequence_number'),
        (N'app', N'DocumentNode', N'ledger_end_transaction_id'),
        (N'app', N'DocumentNode', N'ledger_end_sequence_number'),
        (N'app', N'DocumentPermission', N'Id'),
        (N'app', N'DocumentPermission', N'DocumentId'),
        (N'app', N'DocumentPermission', N'UserId'),
        (N'app', N'DocumentPermission', N'Role'),
        (N'app', N'DocumentPermission', N'LogicalNodeId'),
        (N'app', N'DocumentPermission', N'GrantedAt'),
        (N'app', N'DocumentPermission', N'GrantedByUserId'),
        (N'app', N'DocumentPermission', N'ValidFrom'),
        (N'app', N'DocumentPermission', N'ValidTo'),
        (N'app', N'DocumentPermission', N'ledger_start_transaction_id'),
        (N'app', N'DocumentPermission', N'ledger_start_sequence_number'),
        (N'app', N'DocumentPermission', N'ledger_end_transaction_id'),
        (N'app', N'DocumentPermission', N'ledger_end_sequence_number'),
        (N'app', N'DocumentVersion', N'Id'),
        (N'app', N'DocumentVersion', N'DocumentId'),
        (N'app', N'DocumentVersion', N'Status'),
        (N'app', N'DocumentVersion', N'VersionNumber'),
        (N'app', N'DocumentVersion', N'BasedOnVersionId'),
        (N'app', N'DocumentVersion', N'CreatedAt'),
        (N'app', N'DocumentVersion', N'CreatedByUserId'),
        (N'app', N'DocumentVersion', N'SignedAt'),
        (N'app', N'DocumentVersion', N'SignedContentHash'),
        (N'app', N'DocumentVersion', N'IsCurrent'),
        (N'app', N'DocumentVersion', N'RowVersion'),
        (N'app', N'DocumentVersion', N'ValidFrom'),
        (N'app', N'DocumentVersion', N'ValidTo'),
        (N'app', N'DocumentVersion', N'ledger_start_transaction_id'),
        (N'app', N'DocumentVersion', N'ledger_start_sequence_number'),
        (N'app', N'DocumentVersion', N'ledger_end_transaction_id'),
        (N'app', N'DocumentVersion', N'ledger_end_sequence_number'),
        (N'app', N'Folder', N'Id'),
        (N'app', N'Folder', N'ParentFolderId'),
        (N'app', N'Folder', N'Name'),
        (N'app', N'Folder', N'SortOrder'),
        (N'app', N'Folder', N'CreatedAt'),
        (N'app', N'Folder', N'CreatedByUserId'),
        (N'app', N'Folder', N'RowVersion'),
        (N'app', N'Folder', N'ValidFrom'),
        (N'app', N'Folder', N'ValidTo'),
        (N'app', N'Folder', N'ledger_start_transaction_id'),
        (N'app', N'Folder', N'ledger_start_sequence_number'),
        (N'app', N'Folder', N'ledger_end_transaction_id'),
        (N'app', N'Folder', N'ledger_end_sequence_number'),
        (N'app', N'NodeContent', N'NodeId'),
        (N'app', N'NodeContent', N'DocumentVersionId'),
        (N'app', N'NodeContent', N'LogicalNodeId'),
        (N'app', N'NodeContent', N'SchemaVersion'),
        (N'app', N'NodeContent', N'ContentJson'),
        (N'app', N'NodeContent', N'ContentHtml'),
        (N'app', N'NodeContent', N'PlainText'),
        (N'app', N'NodeContent', N'ContentHash'),
        (N'app', N'NodeContent', N'DerivedStale'),
        (N'app', N'NodeContent', N'ModifiedAt'),
        (N'app', N'NodeContent', N'ModifiedByUserId'),
        (N'app', N'NodeContent', N'RowVersion'),
        (N'app', N'NodeContent', N'ValidFrom'),
        (N'app', N'NodeContent', N'ValidTo'),
        (N'app', N'NodeContent', N'ledger_start_transaction_id'),
        (N'app', N'NodeContent', N'ledger_start_sequence_number'),
        (N'app', N'NodeContent', N'ledger_end_transaction_id'),
        (N'app', N'NodeContent', N'ledger_end_sequence_number'),
        (N'app', N'NodeType', N'Id'),
        (N'app', N'NodeType', N'Code'),
        (N'app', N'NodeType', N'Name'),
        (N'app', N'NodeType', N'Description'),
        (N'app', N'NodeType', N'SortOrder'),
        (N'app', N'NodeType', N'IsActive'),
        (N'app', N'NodeType', N'RowVersion'),
        (N'app', N'NodeType', N'ValidFrom'),
        (N'app', N'NodeType', N'ValidTo'),
        (N'app', N'NodeType', N'ledger_start_transaction_id'),
        (N'app', N'NodeType', N'ledger_start_sequence_number'),
        (N'app', N'NodeType', N'ledger_end_transaction_id'),
        (N'app', N'NodeType', N'ledger_end_sequence_number'),
        (N'app', N'User', N'Id'),
        (N'app', N'User', N'Login'),
        (N'app', N'User', N'DisplayName'),
        (N'app', N'User', N'Email'),
        (N'app', N'User', N'IsAdmin'),
        (N'app', N'User', N'IsActive'),
        (N'app', N'User', N'ValidFrom'),
        (N'app', N'User', N'ValidTo'),
        (N'app', N'User', N'ledger_start_transaction_id'),
        (N'app', N'User', N'ledger_start_sequence_number'),
        (N'app', N'User', N'ledger_end_transaction_id'),
        (N'app', N'User', N'ledger_end_sequence_number'),
        (N'app', N'VersionSignature', N'Id'),
        (N'app', N'VersionSignature', N'DocumentVersionId'),
        (N'app', N'VersionSignature', N'UserId'),
        (N'app', N'VersionSignature', N'SignedAt'),
        (N'app', N'VersionSignature', N'ContentHash'),
        (N'app', N'VersionSignature', N'WithdrawnAt'),
        (N'app', N'VersionSignature', N'Comment'),
        (N'app', N'VersionSignature', N'ValidFrom'),
        (N'app', N'VersionSignature', N'ValidTo'),
        (N'app', N'VersionSignature', N'ledger_start_transaction_id'),
        (N'app', N'VersionSignature', N'ledger_start_sequence_number'),
        (N'app', N'VersionSignature', N'ledger_end_transaction_id'),
        (N'app', N'VersionSignature', N'ledger_end_sequence_number'),
        (N'app', N'VersionStamp', N'DocumentVersionId'),
        (N'app', N'VersionStamp', N'LastChangeLogId'),
        (N'app', N'VersionStamp', N'TamperedAt'),
        (N'app', N'VersionStamp', N'ContentChangeLogId'),
        (N'app', N'VersionStamp', N'LastChangedAt'),
        (N'app', N'VersionStamp', N'ledger_start_transaction_id'),
        (N'app', N'VersionStamp', N'ledger_start_sequence_number'),
        (N'app', N'VersionStamp', N'ledger_end_transaction_id'),
        (N'app', N'VersionStamp', N'ledger_end_sequence_number'),
        (N'audit', N'ChangeLog', N'Id'),
        (N'audit', N'ChangeLog', N'ChangedAt'),
        (N'audit', N'ChangeLog', N'TableName'),
        (N'audit', N'ChangeLog', N'Operation'),
        (N'audit', N'ChangeLog', N'EntityId'),
        (N'audit', N'ChangeLog', N'DocumentId'),
        (N'audit', N'ChangeLog', N'DocumentVersionId'),
        (N'audit', N'ChangeLog', N'LogicalNodeId'),
        (N'audit', N'ChangeLog', N'OldValues'),
        (N'audit', N'ChangeLog', N'NewValues'),
        (N'audit', N'ChangeLog', N'ChangedColumns'),
        (N'audit', N'ChangeLog', N'UserId'),
        (N'audit', N'ChangeLog', N'Source'),
        (N'audit', N'ChangeLog', N'DbLogin'),
        (N'audit', N'ChangeLog', N'AppName'),
        (N'audit', N'ChangeLog', N'CorrelationId'),
        (N'audit', N'ChangeLog', N'OperationContext'),
        (N'audit', N'ChangeLog', N'Ticket'),
        (N'audit', N'ChangeLog', N'Reason'),
        (N'audit', N'ChangeLog', N'ledger_start_transaction_id'),
        (N'audit', N'ChangeLog', N'ledger_start_sequence_number'),
        (N'audit', N'ReconciliationBaseline', N'Id'),
        (N'audit', N'ReconciliationBaseline', N'CreatedAt'),
        (N'audit', N'ReconciliationBaseline', N'Reason'),
        (N'audit', N'ReconciliationBaseline', N'ledger_start_transaction_id'),
        (N'audit', N'ReconciliationBaseline', N'ledger_start_sequence_number'),
        (N'audit', N'ReconciliationFinding', N'Id'),
        (N'audit', N'ReconciliationFinding', N'Kind'),
        (N'audit', N'ReconciliationFinding', N'TableName'),
        (N'audit', N'ReconciliationFinding', N'EntityId'),
        (N'audit', N'ReconciliationFinding', N'DocumentId'),
        (N'audit', N'ReconciliationFinding', N'DocumentVersionId'),
        (N'audit', N'ReconciliationFinding', N'LedgerTransactionId'),
        (N'audit', N'ReconciliationFinding', N'TransactionCommitTime'),
        (N'audit', N'ReconciliationFinding', N'Principal'),
        (N'audit', N'ReconciliationFinding', N'Detail'),
        (N'audit', N'ReconciliationFinding', N'DetectedAt'),
        (N'audit', N'ReconciliationFinding', N'AfterSigning'),
        (N'audit', N'ReconciliationFinding', N'ledger_start_transaction_id'),
        (N'audit', N'ReconciliationFinding', N'ledger_start_sequence_number');

    WITH [created] AS (
        SELECT [h].[object_id], MIN(CONCAT([h].[schema_name] COLLATE DATABASE_DEFAULT, N'.', [h].[table_name] COLLATE DATABASE_DEFAULT)) AS [Name], MIN([h].[schema_name] COLLATE DATABASE_DEFAULT) AS [SchemaName], MIN([h].[table_name] COLLATE DATABASE_DEFAULT) AS [TableName]
        FROM sys.ledger_table_history AS [h]
        WHERE [h].[operation_type_desc] COLLATE DATABASE_DEFAULT = N'CREATE'
        GROUP BY [h].[object_id])
    INSERT INTO [#Finding] ([Kind], [TableName], [EntityId], [LedgerTransactionId], [Detail])
    SELECT 'SchemaTampering', COALESCE([c].[Name], MIN(CONCAT([h].[schema_name] COLLATE DATABASE_DEFAULT, N'.', [h].[table_name] COLLATE DATABASE_DEFAULT))), NULL, [h].[transaction_id],
           LEFT(STRING_AGG(CONCAT(N'Table ', [h].[operation_type_desc] COLLATE DATABASE_DEFAULT, N': ', [h].[schema_name] COLLATE DATABASE_DEFAULT, N'.', [h].[table_name] COLLATE DATABASE_DEFAULT), N'; '), 1000)
    FROM sys.ledger_table_history AS [h]
    LEFT JOIN [created] AS [c] ON [c].[object_id] = [h].[object_id]
    WHERE [h].[operation_type_desc] COLLATE DATABASE_DEFAULT <> N'CREATE'
       OR NOT EXISTS (SELECT 1 FROM [#Allowed] AS [a] WHERE [a].[SchemaName] = [h].[schema_name] COLLATE DATABASE_DEFAULT AND [a].[TableName] = [h].[table_name] COLLATE DATABASE_DEFAULT)
    GROUP BY [h].[object_id], [c].[Name], [h].[transaction_id];

    WITH [created] AS (
        SELECT [h].[object_id], MIN([h].[schema_name] COLLATE DATABASE_DEFAULT) AS [SchemaName], MIN([h].[table_name] COLLATE DATABASE_DEFAULT) AS [TableName]
        FROM sys.ledger_table_history AS [h]
        WHERE [h].[operation_type_desc] COLLATE DATABASE_DEFAULT = N'CREATE'
        GROUP BY [h].[object_id])
    INSERT INTO [#Finding] ([Kind], [TableName], [EntityId], [LedgerTransactionId], [Detail])
    SELECT 'SchemaTampering', CONCAT([c].[SchemaName], N'.', [c].[TableName]), [h].[column_id], [h].[transaction_id],
           LEFT(STRING_AGG(CONCAT(N'Column ', [h].[operation_type_desc] COLLATE DATABASE_DEFAULT, N': ', [h].[column_name] COLLATE DATABASE_DEFAULT), N'; '), 1000)
    FROM sys.ledger_column_history AS [h]
    JOIN [created] AS [c] ON [c].[object_id] = [h].[object_id]
    WHERE [h].[operation_type_desc] COLLATE DATABASE_DEFAULT NOT IN (N'CREATE', N'ADD')
       OR (EXISTS (SELECT 1 FROM [#Allowed] AS [a] WHERE [a].[SchemaName] = [c].[SchemaName] AND [a].[TableName] = [c].[TableName])
           AND NOT EXISTS (SELECT 1 FROM [#Allowed] AS [a]
                           WHERE [a].[SchemaName] = [c].[SchemaName] AND [a].[TableName] = [c].[TableName] AND [a].[ColumnName] = [h].[column_name] COLLATE DATABASE_DEFAULT))
    GROUP BY [c].[SchemaName], [c].[TableName], [h].[column_id], [h].[transaction_id];

    -- Versions a finding affects: its own, plus old and new version of bypassed rows that moved between versions.
    CREATE TABLE [#FindingVersion] ([Key] INT NOT NULL, [VersionId] INT NOT NULL, PRIMARY KEY ([Key], [VersionId]));
    INSERT INTO [#FindingVersion] ([Key], [VersionId])
    SELECT [f].[Key], [f].[DocumentVersionId] FROM [#Finding] AS [f] WHERE [f].[DocumentVersionId] IS NOT NULL
    UNION
    SELECT [f].[Key], [x].[VersionId]
    FROM [#Finding] AS [f]
    JOIN [#Change] AS [c] ON [f].[Kind] = 'TriggerBypass' AND [c].[TableName] = [f].[TableName] AND [c].[EntityId] = [f].[EntityId] AND [c].[TransactionId] = [f].[LedgerTransactionId]
    CROSS APPLY (VALUES ([c].[VersionNew]), ([c].[VersionOld])) AS [x] ([VersionId])
    WHERE [x].[VersionId] IS NOT NULL;

    -- Ledger signing time: commit time of the first transaction that made the version Signed (not the editable SignedAt).
    CREATE TABLE [#Signing] ([VersionId] INT NOT NULL PRIMARY KEY, [CommitTime] DATETIME2 (7) NOT NULL);
    INSERT INTO [#Signing] ([VersionId], [CommitTime])
    SELECT [l].[Id], MIN([t].[commit_time])
    FROM [app].[DocumentVersion_Ledger] AS [l]
    JOIN sys.database_ledger_transactions AS [t] ON [t].[transaction_id] = [l].[ledger_transaction_id]
    WHERE [l].[ledger_operation_type] = 1 AND [l].[Status] = 2 AND [l].[Id] IN (SELECT [VersionId] FROM [#FindingVersion])
    GROUP BY [l].[Id];

    DECLARE @New TABLE ([Key] INT NOT NULL, [Id] BIGINT NOT NULL);
    DECLARE @Logged TABLE ([Id] BIGINT NOT NULL, [FindingId] INT NOT NULL, [VersionId] INT NOT NULL);

    BEGIN TRANSACTION;

    -- One run at a time, so the duplicate check below sees every finding.
    EXEC sys.sp_getapplock @Resource = N'audit.usp_ReconcileLedger', @LockMode = 'Exclusive', @LockOwner = 'Transaction';

    -- Append-only tables allow INSERT only; new findings are mapped back to #Finding by their identity (unique per run).
    DECLARE @Inserted TABLE ([Id] BIGINT NOT NULL, [Kind] VARCHAR (40) NOT NULL, [TableName] NVARCHAR (256) NULL, [EntityId] INT NULL,
                             [LedgerTransactionId] BIGINT NULL, [Detail] NVARCHAR (1000) NULL);
    INSERT INTO [audit].[ReconciliationFinding]
        ([Kind], [TableName], [EntityId], [DocumentId], [DocumentVersionId], [LedgerTransactionId], [TransactionCommitTime], [Principal], [Detail], [AfterSigning])
    OUTPUT INSERTED.[Id], INSERTED.[Kind], INSERTED.[TableName], INSERTED.[EntityId], INSERTED.[LedgerTransactionId], INSERTED.[Detail] INTO @Inserted
    SELECT [f].[Kind], [f].[TableName], [f].[EntityId], [f].[DocumentId], [f].[DocumentVersionId], [f].[LedgerTransactionId],
           [t].[commit_time], [t].[principal_name] COLLATE DATABASE_DEFAULT, [f].[Detail],
           CASE WHEN [s].[CommitTime] IS NOT NULL AND [t].[commit_time] >= [s].[CommitTime] THEN 1 ELSE 0 END
    FROM [#Finding] AS [f]
    LEFT JOIN sys.database_ledger_transactions AS [t] ON [t].[transaction_id] = [f].[LedgerTransactionId]
    LEFT JOIN [#Signing] AS [s] ON [s].[VersionId] = [f].[DocumentVersionId]
    WHERE NOT EXISTS (SELECT 1 FROM [audit].[ReconciliationFinding] AS [e]
                      WHERE [e].[Kind] = [f].[Kind] AND [e].[TableName] IS NOT DISTINCT FROM [f].[TableName]
                        AND [e].[EntityId] IS NOT DISTINCT FROM [f].[EntityId]
                        AND [e].[LedgerTransactionId] IS NOT DISTINCT FROM [f].[LedgerTransactionId]
                        AND ([e].[LedgerTransactionId] IS NOT NULL OR [e].[Detail] IS NOT DISTINCT FROM [f].[Detail]));

    INSERT INTO @New ([Key], [Id])
    SELECT [f].[Key], [i].[Id]
    FROM @Inserted AS [i]
    JOIN [#Finding] AS [f]
        ON [f].[Kind] = [i].[Kind] AND [f].[TableName] IS NOT DISTINCT FROM [i].[TableName] AND [f].[EntityId] IS NOT DISTINCT FROM [i].[EntityId]
       AND [f].[LedgerTransactionId] IS NOT DISTINCT FROM [i].[LedgerTransactionId] AND [f].[Detail] IS NOT DISTINCT FROM [i].[Detail];

    -- Effects, per affected (still existing) version: a ChangeLog row, VersionStamp advanced, TamperedAt for Signed versions.
    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [NewValues], [UserId], [Source], [DbLogin], [AppName],
         [CorrelationId], [OperationContext])
    OUTPUT INSERTED.[Id], INSERTED.[EntityId], INSERTED.[DocumentVersionId] INTO @Logged ([Id], [FindingId], [VersionId])
    SELECT N'audit.ReconciliationFinding', 'I', CAST([n].[Id] AS INT), [v].[DocumentId], [v].[Id],
           (SELECT [n].[Id] AS [Id], [f].[Kind] AS [Kind], [f].[TableName] AS [TableName], [f].[EntityId] AS [EntityId],
                   [f].[LedgerTransactionId] AS [LedgerTransactionId]
            FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES),
           [ctx].[UserId], 'App', [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], N'Reconciliation'
    FROM @New AS [n]
    JOIN [#Finding] AS [f] ON [f].[Key] = [n].[Key]
    JOIN [#FindingVersion] AS [fv] ON [fv].[Key] = [f].[Key]
    JOIN [app].[DocumentVersion] AS [v] ON [v].[Id] = [fv].[VersionId]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx];

    MERGE [app].[VersionStamp] WITH (HOLDLOCK) AS [target]
    USING (SELECT [l].[VersionId], MAX([l].[Id]) AS [LastChangeLogId],
                  MIN(CASE WHEN [v].[Status] = 2 AND [t].[commit_time] >= [s].[CommitTime] THEN [t].[commit_time] END) AS [TamperedAt]
           FROM @Logged AS [l]
           JOIN @New AS [n] ON [n].[Id] = [l].[FindingId]
           JOIN [#Finding] AS [f] ON [f].[Key] = [n].[Key]
           JOIN [app].[DocumentVersion] AS [v] ON [v].[Id] = [l].[VersionId]
           LEFT JOIN sys.database_ledger_transactions AS [t] ON [t].[transaction_id] = [f].[LedgerTransactionId]
           LEFT JOIN [#Signing] AS [s] ON [s].[VersionId] = [l].[VersionId]
           GROUP BY [l].[VersionId]) AS [source]
    ON [target].[DocumentVersionId] = [source].[VersionId]
    WHEN MATCHED THEN
        -- A finding may mean content changed outside the triggers: advance the content stamp too (content-hash cache).
        UPDATE SET [LastChangeLogId] = CASE WHEN [source].[LastChangeLogId] > [target].[LastChangeLogId] THEN [source].[LastChangeLogId] ELSE [target].[LastChangeLogId] END,
                   [ContentChangeLogId] = CASE WHEN [source].[LastChangeLogId] > COALESCE([target].[ContentChangeLogId], 0) THEN [source].[LastChangeLogId] ELSE [target].[ContentChangeLogId] END,
                   [TamperedAt] = COALESCE([target].[TamperedAt], [source].[TamperedAt])
    WHEN NOT MATCHED BY TARGET THEN
        INSERT ([DocumentVersionId], [LastChangeLogId], [ContentChangeLogId], [TamperedAt])
        VALUES ([source].[VersionId], [source].[LastChangeLogId], [source].[LastChangeLogId], [source].[TamperedAt]);

    -- Forged ContentHtml/PlainText of bypassed content is re-rendered by the API (T09).
    UPDATE [nc]
    SET [DerivedStale] = 1
    FROM [app].[NodeContent] AS [nc]
    JOIN [#Finding] AS [f] ON [f].[MarksDerivedStale] = 1 AND [f].[EntityId] = [nc].[NodeId]
    JOIN @New AS [n] ON [n].[Key] = [f].[Key]
    WHERE [nc].[DerivedStale] = 0;

    COMMIT TRANSACTION;

    SET @NewFindings = (SELECT COUNT(*) FROM @New);
END;
