-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_ContentStyle_Audit]
ON [app].[ContentStyle]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.ContentStyle',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        NULL,
        NULL,
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[StyleId] AS [StyleId], [d].[Name] AS [Name], [d].[Kind] AS [Kind], [d].[BasedOnStyleId] AS [BasedOnStyleId], [d].[PropertiesJson] AS [PropertiesJson], [d].[IsBuiltIn] AS [IsBuiltIn], [d].[IsActive] AS [IsActive] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[StyleId] AS [StyleId], [i].[Name] AS [Name], [i].[Kind] AS [Kind], [i].[BasedOnStyleId] AS [BasedOnStyleId], [i].[PropertiesJson] AS [PropertiesJson], [i].[IsBuiltIn] AS [IsBuiltIn], [i].[IsActive] AS [IsActive] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN CAST([i].[StyleId] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[StyleId] AS VARBINARY (MAX)) THEN N'StyleId' END,
                   CASE WHEN CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX)) THEN N'Name' END,
                   CASE WHEN [i].[Kind] IS DISTINCT FROM [d].[Kind] THEN N'Kind' END,
                   CASE WHEN CAST([i].[BasedOnStyleId] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[BasedOnStyleId] AS VARBINARY (MAX)) THEN N'BasedOnStyleId' END,
                   CASE WHEN CAST([i].[PropertiesJson] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[PropertiesJson] AS VARBINARY (MAX)) THEN N'PropertiesJson' END,
                   CASE WHEN [i].[IsBuiltIn] IS DISTINCT FROM [d].[IsBuiltIn] THEN N'IsBuiltIn' END,
                   CASE WHEN [i].[IsActive] IS DISTINCT FROM [d].[IsActive] THEN N'IsActive' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR CAST([i].[StyleId] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[StyleId] AS VARBINARY (MAX))
           OR CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX))
           OR [i].[Kind] IS DISTINCT FROM [d].[Kind]
           OR CAST([i].[BasedOnStyleId] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[BasedOnStyleId] AS VARBINARY (MAX))
           OR CAST([i].[PropertiesJson] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[PropertiesJson] AS VARBINARY (MAX))
           OR [i].[IsBuiltIn] IS DISTINCT FROM [d].[IsBuiltIn]
           OR [i].[IsActive] IS DISTINCT FROM [d].[IsActive]
    ;
END;
