-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_Comment_Audit]
ON [app].[Comment]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.Comment',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        COALESCE([i].[DocumentId], [d].[DocumentId]),
        COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId]),
        COALESCE([i].[LogicalNodeId], [d].[LogicalNodeId]),
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[DocumentId] AS [DocumentId], [d].[DocumentVersionId] AS [DocumentVersionId], [d].[LogicalNodeId] AS [LogicalNodeId], [d].[ParentCommentId] AS [ParentCommentId], [d].[AuthorUserId] AS [AuthorUserId], [d].[Body] AS [Body], [d].[CreatedAt] AS [CreatedAt], [d].[EditedAt] AS [EditedAt], [d].[DeletedAt] AS [DeletedAt], [d].[ResolvedAt] AS [ResolvedAt], [d].[ResolvedByUserId] AS [ResolvedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[DocumentId] AS [DocumentId], [i].[DocumentVersionId] AS [DocumentVersionId], [i].[LogicalNodeId] AS [LogicalNodeId], [i].[ParentCommentId] AS [ParentCommentId], [i].[AuthorUserId] AS [AuthorUserId], [i].[Body] AS [Body], [i].[CreatedAt] AS [CreatedAt], [i].[EditedAt] AS [EditedAt], [i].[DeletedAt] AS [DeletedAt], [i].[ResolvedAt] AS [ResolvedAt], [i].[ResolvedByUserId] AS [ResolvedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId] THEN N'DocumentId' END,
                   CASE WHEN [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId] THEN N'DocumentVersionId' END,
                   CASE WHEN [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId] THEN N'LogicalNodeId' END,
                   CASE WHEN [i].[ParentCommentId] IS DISTINCT FROM [d].[ParentCommentId] THEN N'ParentCommentId' END,
                   CASE WHEN [i].[AuthorUserId] IS DISTINCT FROM [d].[AuthorUserId] THEN N'AuthorUserId' END,
                   CASE WHEN CAST([i].[Body] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Body] AS VARBINARY (MAX)) THEN N'Body' END,
                   CASE WHEN [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt] THEN N'CreatedAt' END,
                   CASE WHEN [i].[EditedAt] IS DISTINCT FROM [d].[EditedAt] THEN N'EditedAt' END,
                   CASE WHEN [i].[DeletedAt] IS DISTINCT FROM [d].[DeletedAt] THEN N'DeletedAt' END,
                   CASE WHEN [i].[ResolvedAt] IS DISTINCT FROM [d].[ResolvedAt] THEN N'ResolvedAt' END,
                   CASE WHEN [i].[ResolvedByUserId] IS DISTINCT FROM [d].[ResolvedByUserId] THEN N'ResolvedByUserId' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]
           OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
           OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
           OR [i].[ParentCommentId] IS DISTINCT FROM [d].[ParentCommentId]
           OR [i].[AuthorUserId] IS DISTINCT FROM [d].[AuthorUserId]
           OR CAST([i].[Body] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Body] AS VARBINARY (MAX))
           OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
           OR [i].[EditedAt] IS DISTINCT FROM [d].[EditedAt]
           OR [i].[DeletedAt] IS DISTINCT FROM [d].[DeletedAt]
           OR [i].[ResolvedAt] IS DISTINCT FROM [d].[ResolvedAt]
           OR [i].[ResolvedByUserId] IS DISTINCT FROM [d].[ResolvedByUserId]
    ;
END;
