-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_DocumentVersion_Audit]
ON [app].[DocumentVersion]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    DECLARE @Logged TABLE ([Id] BIGINT NOT NULL, [EntityId] INT NOT NULL, [ChangedAt] DATETIME2 (7) NOT NULL);

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    OUTPUT INSERTED.[Id], INSERTED.[EntityId], INSERTED.[ChangedAt] INTO @Logged ([Id], [EntityId], [ChangedAt])
    SELECT
        N'app.DocumentVersion',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        COALESCE([i].[DocumentId], [d].[DocumentId]),
        COALESCE([i].[Id], [d].[Id]),
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[DocumentId] AS [DocumentId], [d].[Status] AS [Status], [d].[VersionNumber] AS [VersionNumber], [d].[BasedOnVersionId] AS [BasedOnVersionId], [d].[CreatedAt] AS [CreatedAt], [d].[CreatedByUserId] AS [CreatedByUserId], [d].[SignedAt] AS [SignedAt], [d].[SignedContentHash] AS [SignedContentHash], [d].[IsCurrent] AS [IsCurrent] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[DocumentId] AS [DocumentId], [i].[Status] AS [Status], [i].[VersionNumber] AS [VersionNumber], [i].[BasedOnVersionId] AS [BasedOnVersionId], [i].[CreatedAt] AS [CreatedAt], [i].[CreatedByUserId] AS [CreatedByUserId], [i].[SignedAt] AS [SignedAt], [i].[SignedContentHash] AS [SignedContentHash], [i].[IsCurrent] AS [IsCurrent] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId] THEN N'DocumentId' END,
                   CASE WHEN [i].[Status] IS DISTINCT FROM [d].[Status] THEN N'Status' END,
                   CASE WHEN [i].[VersionNumber] IS DISTINCT FROM [d].[VersionNumber] THEN N'VersionNumber' END,
                   CASE WHEN [i].[BasedOnVersionId] IS DISTINCT FROM [d].[BasedOnVersionId] THEN N'BasedOnVersionId' END,
                   CASE WHEN [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt] THEN N'CreatedAt' END,
                   CASE WHEN [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId] THEN N'CreatedByUserId' END,
                   CASE WHEN [i].[SignedAt] IS DISTINCT FROM [d].[SignedAt] THEN N'SignedAt' END,
                   CASE WHEN [i].[SignedContentHash] IS DISTINCT FROM [d].[SignedContentHash] THEN N'SignedContentHash' END,
                   CASE WHEN [i].[IsCurrent] IS DISTINCT FROM [d].[IsCurrent] THEN N'IsCurrent' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]
           OR [i].[Status] IS DISTINCT FROM [d].[Status]
           OR [i].[VersionNumber] IS DISTINCT FROM [d].[VersionNumber]
           OR [i].[BasedOnVersionId] IS DISTINCT FROM [d].[BasedOnVersionId]
           OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
           OR [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId]
           OR [i].[SignedAt] IS DISTINCT FROM [d].[SignedAt]
           OR [i].[SignedContentHash] IS DISTINCT FROM [d].[SignedContentHash]
           OR [i].[IsCurrent] IS DISTINCT FROM [d].[IsCurrent]
    ;

    -- T03 §2b: advance the per-version stamp (cache key/ETag) of every version the change touches — old and new version
    -- for rows that move between versions — and record the first tampering with a Signed version (TamperedAt = ChangedAt of that log row).
    MERGE [app].[VersionStamp] WITH (HOLDLOCK) AS [target]
    USING (
        SELECT [x].[DocumentVersionId], MAX([l].[Id]) AS [LastChangeLogId], MIN(CASE WHEN [d].[Status] = 2 AND ([i].[Id] IS NULL OR [i].[Status] IS DISTINCT FROM [d].[Status] OR [i].[VersionNumber] IS DISTINCT FROM [d].[VersionNumber] OR [i].[SignedAt] IS DISTINCT FROM [d].[SignedAt] OR [i].[SignedContentHash] IS DISTINCT FROM [d].[SignedContentHash] OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]) THEN [l].[ChangedAt] END) AS [TamperedAt]
        FROM @Logged AS [l]
        LEFT JOIN inserted AS [i] ON [i].[Id] = [l].[EntityId]
        LEFT JOIN deleted AS [d] ON [d].[Id] = [l].[EntityId]
        CROSS APPLY (VALUES ([i].[Id]), ([d].[Id])) AS [x] ([DocumentVersionId])
        JOIN [app].[DocumentVersion] AS [v] ON [v].[Id] = [x].[DocumentVersionId]
        GROUP BY [x].[DocumentVersionId]) AS [source]
    ON [target].[DocumentVersionId] = [source].[DocumentVersionId]
    WHEN MATCHED THEN
        UPDATE SET [LastChangeLogId] = CASE WHEN [source].[LastChangeLogId] > [target].[LastChangeLogId] THEN [source].[LastChangeLogId] ELSE [target].[LastChangeLogId] END,
                   [TamperedAt] = COALESCE([target].[TamperedAt], [source].[TamperedAt])
    WHEN NOT MATCHED BY TARGET THEN
        INSERT ([DocumentVersionId], [LastChangeLogId], [TamperedAt])
        VALUES ([source].[DocumentVersionId], [source].[LastChangeLogId], [source].[TamperedAt]);
END;
