-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_DocumentPermission_Audit]
ON [app].[DocumentPermission]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.DocumentPermission',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        COALESCE([i].[DocumentId], [d].[DocumentId]),
        NULL,
        COALESCE([i].[LogicalNodeId], [d].[LogicalNodeId]),
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[DocumentId] AS [DocumentId], [d].[UserId] AS [UserId], [d].[Role] AS [Role], [d].[LogicalNodeId] AS [LogicalNodeId], [d].[GrantedAt] AS [GrantedAt], [d].[GrantedByUserId] AS [GrantedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[DocumentId] AS [DocumentId], [i].[UserId] AS [UserId], [i].[Role] AS [Role], [i].[LogicalNodeId] AS [LogicalNodeId], [i].[GrantedAt] AS [GrantedAt], [i].[GrantedByUserId] AS [GrantedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId] THEN N'DocumentId' END,
                   CASE WHEN [i].[UserId] IS DISTINCT FROM [d].[UserId] THEN N'UserId' END,
                   CASE WHEN [i].[Role] IS DISTINCT FROM [d].[Role] THEN N'Role' END,
                   CASE WHEN [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId] THEN N'LogicalNodeId' END,
                   CASE WHEN [i].[GrantedAt] IS DISTINCT FROM [d].[GrantedAt] THEN N'GrantedAt' END,
                   CASE WHEN [i].[GrantedByUserId] IS DISTINCT FROM [d].[GrantedByUserId] THEN N'GrantedByUserId' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]
           OR [i].[UserId] IS DISTINCT FROM [d].[UserId]
           OR [i].[Role] IS DISTINCT FROM [d].[Role]
           OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
           OR [i].[GrantedAt] IS DISTINCT FROM [d].[GrantedAt]
           OR [i].[GrantedByUserId] IS DISTINCT FROM [d].[GrantedByUserId];
END;
