-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_DocumentNode_Audit]
ON [app].[DocumentNode]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    DECLARE @Logged TABLE ([Id] BIGINT NOT NULL, [EntityId] INT NOT NULL, [ChangedAt] DATETIME2 (7) NOT NULL);

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    OUTPUT INSERTED.[Id], INSERTED.[EntityId], INSERTED.[ChangedAt] INTO @Logged ([Id], [EntityId], [ChangedAt])
    SELECT
        N'app.DocumentNode',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        (SELECT [v].[DocumentId] FROM [app].[DocumentVersion] AS [v] WHERE [v].[Id] = COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId])),
        COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId]),
        COALESCE([i].[LogicalNodeId], [d].[LogicalNodeId]),
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[DocumentVersionId] AS [DocumentVersionId], [d].[LogicalNodeId] AS [LogicalNodeId], [d].[ParentNodeId] AS [ParentNodeId], [d].[NodeTypeId] AS [NodeTypeId], [d].[Title] AS [Title], [d].[SortOrder] AS [SortOrder], [d].[CreatedAt] AS [CreatedAt], [d].[CreatedByUserId] AS [CreatedByUserId], [d].[ModifiedAt] AS [ModifiedAt], [d].[ModifiedByUserId] AS [ModifiedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[DocumentVersionId] AS [DocumentVersionId], [i].[LogicalNodeId] AS [LogicalNodeId], [i].[ParentNodeId] AS [ParentNodeId], [i].[NodeTypeId] AS [NodeTypeId], [i].[Title] AS [Title], [i].[SortOrder] AS [SortOrder], [i].[CreatedAt] AS [CreatedAt], [i].[CreatedByUserId] AS [CreatedByUserId], [i].[ModifiedAt] AS [ModifiedAt], [i].[ModifiedByUserId] AS [ModifiedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId] THEN N'DocumentVersionId' END,
                   CASE WHEN [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId] THEN N'LogicalNodeId' END,
                   CASE WHEN [i].[ParentNodeId] IS DISTINCT FROM [d].[ParentNodeId] THEN N'ParentNodeId' END,
                   CASE WHEN [i].[NodeTypeId] IS DISTINCT FROM [d].[NodeTypeId] THEN N'NodeTypeId' END,
                   CASE WHEN CAST([i].[Title] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Title] AS VARBINARY (MAX)) THEN N'Title' END,
                   CASE WHEN [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder] THEN N'SortOrder' END,
                   CASE WHEN [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt] THEN N'CreatedAt' END,
                   CASE WHEN [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId] THEN N'CreatedByUserId' END,
                   CASE WHEN [i].[ModifiedAt] IS DISTINCT FROM [d].[ModifiedAt] THEN N'ModifiedAt' END,
                   CASE WHEN [i].[ModifiedByUserId] IS DISTINCT FROM [d].[ModifiedByUserId] THEN N'ModifiedByUserId' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
           OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
           OR [i].[ParentNodeId] IS DISTINCT FROM [d].[ParentNodeId]
           OR [i].[NodeTypeId] IS DISTINCT FROM [d].[NodeTypeId]
           OR CAST([i].[Title] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Title] AS VARBINARY (MAX))
           OR [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder]
           OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
           OR [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId]
           OR [i].[ModifiedAt] IS DISTINCT FROM [d].[ModifiedAt]
           OR [i].[ModifiedByUserId] IS DISTINCT FROM [d].[ModifiedByUserId]
    ;

    -- T03 §2b: advance the per-version stamp (cache key/ETag) of every version the change touches — old and new version
    -- for rows that move between versions — and record the first tampering with a Signed version (TamperedAt = ChangedAt of that log row).
    MERGE [app].[VersionStamp] WITH (HOLDLOCK) AS [target]
    USING (
        SELECT [x].[DocumentVersionId], MAX([l].[Id]) AS [LastChangeLogId], MIN(CASE WHEN [v].[Status] = 2 THEN [l].[ChangedAt] END) AS [TamperedAt]
        FROM @Logged AS [l]
        LEFT JOIN inserted AS [i] ON [i].[Id] = [l].[EntityId]
        LEFT JOIN deleted AS [d] ON [d].[Id] = [l].[EntityId]
        CROSS APPLY (VALUES ([i].[DocumentVersionId]), ([d].[DocumentVersionId])) AS [x] ([DocumentVersionId])
        JOIN [app].[DocumentVersion] AS [v] ON [v].[Id] = [x].[DocumentVersionId]
        CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
        GROUP BY [x].[DocumentVersionId]) AS [source]
    ON [target].[DocumentVersionId] = [source].[DocumentVersionId]
    WHEN MATCHED THEN
        UPDATE SET [LastChangeLogId] = CASE WHEN [source].[LastChangeLogId] > [target].[LastChangeLogId] THEN [source].[LastChangeLogId] ELSE [target].[LastChangeLogId] END,
                   [TamperedAt] = COALESCE([target].[TamperedAt], [source].[TamperedAt])
    WHEN NOT MATCHED BY TARGET THEN
        INSERT ([DocumentVersionId], [LastChangeLogId], [TamperedAt])
        VALUES ([source].[DocumentVersionId], [source].[LastChangeLogId], [source].[TamperedAt]);
END;
