-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_Document_Audit]
ON [app].[Document]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.Document',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        COALESCE([i].[Id], [d].[Id]),
        NULL,
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[FolderId] AS [FolderId], [d].[Title] AS [Title], [d].[OwnerUserId] AS [OwnerUserId], [d].[CreatedAt] AS [CreatedAt], [d].[DeletedAt] AS [DeletedAt], [d].[DeletedByUserId] AS [DeletedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[FolderId] AS [FolderId], [i].[Title] AS [Title], [i].[OwnerUserId] AS [OwnerUserId], [i].[CreatedAt] AS [CreatedAt], [i].[DeletedAt] AS [DeletedAt], [i].[DeletedByUserId] AS [DeletedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[FolderId] IS DISTINCT FROM [d].[FolderId] THEN N'FolderId' END,
                   CASE WHEN CAST([i].[Title] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Title] AS VARBINARY (MAX)) THEN N'Title' END,
                   CASE WHEN [i].[OwnerUserId] IS DISTINCT FROM [d].[OwnerUserId] THEN N'OwnerUserId' END,
                   CASE WHEN [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt] THEN N'CreatedAt' END,
                   CASE WHEN [i].[DeletedAt] IS DISTINCT FROM [d].[DeletedAt] THEN N'DeletedAt' END,
                   CASE WHEN [i].[DeletedByUserId] IS DISTINCT FROM [d].[DeletedByUserId] THEN N'DeletedByUserId' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[FolderId] IS DISTINCT FROM [d].[FolderId]
           OR CAST([i].[Title] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Title] AS VARBINARY (MAX))
           OR [i].[OwnerUserId] IS DISTINCT FROM [d].[OwnerUserId]
           OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
           OR [i].[DeletedAt] IS DISTINCT FROM [d].[DeletedAt]
           OR [i].[DeletedByUserId] IS DISTINCT FROM [d].[DeletedByUserId]
    ;
END;
