-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_ExportJob_Audit]
ON [app].[ExportJob]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.ExportJob',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        COALESCE([i].[DocumentId], [d].[DocumentId]),
        COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId]),
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[DocumentId] AS [DocumentId], [d].[DocumentVersionId] AS [DocumentVersionId], [d].[LogicalNodeId] AS [LogicalNodeId], [d].[OptionsJson] AS [OptionsJson], [d].[Status] AS [Status], [d].[Progress] AS [Progress], [d].[RequestedByUserId] AS [RequestedByUserId], [d].[RequestedAt] AS [RequestedAt], [d].[StartedAt] AS [StartedAt], [d].[FinishedAt] AS [FinishedAt], [d].[Error] AS [Error], [d].[BlobPath] AS [BlobPath], [d].[FileName] AS [FileName], [d].[FileSize] AS [FileSize], [d].[CacheKey] AS [CacheKey] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[DocumentId] AS [DocumentId], [i].[DocumentVersionId] AS [DocumentVersionId], [i].[LogicalNodeId] AS [LogicalNodeId], [i].[OptionsJson] AS [OptionsJson], [i].[Status] AS [Status], [i].[Progress] AS [Progress], [i].[RequestedByUserId] AS [RequestedByUserId], [i].[RequestedAt] AS [RequestedAt], [i].[StartedAt] AS [StartedAt], [i].[FinishedAt] AS [FinishedAt], [i].[Error] AS [Error], [i].[BlobPath] AS [BlobPath], [i].[FileName] AS [FileName], [i].[FileSize] AS [FileSize], [i].[CacheKey] AS [CacheKey] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId] THEN N'DocumentId' END,
                   CASE WHEN [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId] THEN N'DocumentVersionId' END,
                   CASE WHEN [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId] THEN N'LogicalNodeId' END,
                   CASE WHEN CAST([i].[OptionsJson] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[OptionsJson] AS VARBINARY (MAX)) THEN N'OptionsJson' END,
                   CASE WHEN [i].[Status] IS DISTINCT FROM [d].[Status] THEN N'Status' END,
                   CASE WHEN [i].[Progress] IS DISTINCT FROM [d].[Progress] THEN N'Progress' END,
                   CASE WHEN [i].[RequestedByUserId] IS DISTINCT FROM [d].[RequestedByUserId] THEN N'RequestedByUserId' END,
                   CASE WHEN [i].[RequestedAt] IS DISTINCT FROM [d].[RequestedAt] THEN N'RequestedAt' END,
                   CASE WHEN [i].[StartedAt] IS DISTINCT FROM [d].[StartedAt] THEN N'StartedAt' END,
                   CASE WHEN [i].[FinishedAt] IS DISTINCT FROM [d].[FinishedAt] THEN N'FinishedAt' END,
                   CASE WHEN CAST([i].[Error] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Error] AS VARBINARY (MAX)) THEN N'Error' END,
                   CASE WHEN CAST([i].[BlobPath] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[BlobPath] AS VARBINARY (MAX)) THEN N'BlobPath' END,
                   CASE WHEN CAST([i].[FileName] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[FileName] AS VARBINARY (MAX)) THEN N'FileName' END,
                   CASE WHEN [i].[FileSize] IS DISTINCT FROM [d].[FileSize] THEN N'FileSize' END,
                   CASE WHEN CAST([i].[CacheKey] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[CacheKey] AS VARBINARY (MAX)) THEN N'CacheKey' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[DocumentId] IS DISTINCT FROM [d].[DocumentId]
           OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
           OR [i].[LogicalNodeId] IS DISTINCT FROM [d].[LogicalNodeId]
           OR CAST([i].[OptionsJson] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[OptionsJson] AS VARBINARY (MAX))
           OR [i].[Status] IS DISTINCT FROM [d].[Status]
           OR [i].[Progress] IS DISTINCT FROM [d].[Progress]
           OR [i].[RequestedByUserId] IS DISTINCT FROM [d].[RequestedByUserId]
           OR [i].[RequestedAt] IS DISTINCT FROM [d].[RequestedAt]
           OR [i].[StartedAt] IS DISTINCT FROM [d].[StartedAt]
           OR [i].[FinishedAt] IS DISTINCT FROM [d].[FinishedAt]
           OR CAST([i].[Error] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Error] AS VARBINARY (MAX))
           OR CAST([i].[BlobPath] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[BlobPath] AS VARBINARY (MAX))
           OR CAST([i].[FileName] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[FileName] AS VARBINARY (MAX))
           OR [i].[FileSize] IS DISTINCT FROM [d].[FileSize]
           OR CAST([i].[CacheKey] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[CacheKey] AS VARBINARY (MAX))
    ;
END;
