-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_Folder_Audit]
ON [app].[Folder]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.Folder',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        NULL,
        NULL,
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[ParentFolderId] AS [ParentFolderId], [d].[Name] AS [Name], [d].[SortOrder] AS [SortOrder], [d].[CreatedAt] AS [CreatedAt], [d].[CreatedByUserId] AS [CreatedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[ParentFolderId] AS [ParentFolderId], [i].[Name] AS [Name], [i].[SortOrder] AS [SortOrder], [i].[CreatedAt] AS [CreatedAt], [i].[CreatedByUserId] AS [CreatedByUserId] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[ParentFolderId] IS DISTINCT FROM [d].[ParentFolderId] THEN N'ParentFolderId' END,
                   CASE WHEN CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX)) THEN N'Name' END,
                   CASE WHEN [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder] THEN N'SortOrder' END,
                   CASE WHEN [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt] THEN N'CreatedAt' END,
                   CASE WHEN [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId] THEN N'CreatedByUserId' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[ParentFolderId] IS DISTINCT FROM [d].[ParentFolderId]
           OR CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX))
           OR [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder]
           OR [i].[CreatedAt] IS DISTINCT FROM [d].[CreatedAt]
           OR [i].[CreatedByUserId] IS DISTINCT FROM [d].[CreatedByUserId];
END;
