-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_NodeType_Audit]
ON [app].[NodeType]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.NodeType',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        NULL,
        NULL,
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[Code] AS [Code], [d].[Name] AS [Name], [d].[Description] AS [Description], [d].[SortOrder] AS [SortOrder], [d].[IsActive] AS [IsActive] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[Code] AS [Code], [i].[Name] AS [Name], [i].[Description] AS [Description], [i].[SortOrder] AS [SortOrder], [i].[IsActive] AS [IsActive] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN CAST([i].[Code] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Code] AS VARBINARY (MAX)) THEN N'Code' END,
                   CASE WHEN CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX)) THEN N'Name' END,
                   CASE WHEN CAST([i].[Description] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Description] AS VARBINARY (MAX)) THEN N'Description' END,
                   CASE WHEN [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder] THEN N'SortOrder' END,
                   CASE WHEN [i].[IsActive] IS DISTINCT FROM [d].[IsActive] THEN N'IsActive' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR CAST([i].[Code] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Code] AS VARBINARY (MAX))
           OR CAST([i].[Name] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Name] AS VARBINARY (MAX))
           OR CAST([i].[Description] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Description] AS VARBINARY (MAX))
           OR [i].[SortOrder] IS DISTINCT FROM [d].[SortOrder]
           OR [i].[IsActive] IS DISTINCT FROM [d].[IsActive];
END;
