-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_User_Audit]
ON [app].[User]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    SELECT
        N'app.User',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        NULL,
        NULL,
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[Login] AS [Login], [d].[DisplayName] AS [DisplayName], [d].[Email] AS [Email], [d].[IsAdmin] AS [IsAdmin], [d].[IsActive] AS [IsActive] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[Login] AS [Login], [i].[DisplayName] AS [DisplayName], [i].[Email] AS [Email], [i].[IsAdmin] AS [IsAdmin], [i].[IsActive] AS [IsActive] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN CAST([i].[Login] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Login] AS VARBINARY (MAX)) THEN N'Login' END,
                   CASE WHEN CAST([i].[DisplayName] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[DisplayName] AS VARBINARY (MAX)) THEN N'DisplayName' END,
                   CASE WHEN CAST([i].[Email] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Email] AS VARBINARY (MAX)) THEN N'Email' END,
                   CASE WHEN [i].[IsAdmin] IS DISTINCT FROM [d].[IsAdmin] THEN N'IsAdmin' END,
                   CASE WHEN [i].[IsActive] IS DISTINCT FROM [d].[IsActive] THEN N'IsActive' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR CAST([i].[Login] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Login] AS VARBINARY (MAX))
           OR CAST([i].[DisplayName] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[DisplayName] AS VARBINARY (MAX))
           OR CAST([i].[Email] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Email] AS VARBINARY (MAX))
           OR [i].[IsAdmin] IS DISTINCT FROM [d].[IsAdmin]
           OR [i].[IsActive] IS DISTINCT FROM [d].[IsActive]
    ;
END;
