-- <auto-generated> by database/tools/GenerateAuditTriggers.cs — do not edit by hand. </auto-generated>
CREATE TRIGGER [app].[TR_VersionSignature_Audit]
ON [app].[VersionSignature]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM inserted) AND NOT EXISTS (SELECT 1 FROM deleted)
        RETURN;

    DECLARE @Logged TABLE ([Id] BIGINT NOT NULL, [EntityId] INT NOT NULL);

    INSERT INTO [audit].[ChangeLog]
        ([TableName], [Operation], [EntityId], [DocumentId], [DocumentVersionId], [LogicalNodeId], [OldValues], [NewValues],
         [ChangedColumns], [UserId], [Source], [DbLogin], [AppName], [CorrelationId], [OperationContext], [Ticket], [Reason])
    OUTPUT INSERTED.[Id], INSERTED.[EntityId] INTO @Logged ([Id], [EntityId])
    SELECT
        N'app.VersionSignature',
        CASE WHEN [d].[Id] IS NULL THEN 'I' WHEN [i].[Id] IS NULL THEN 'D' ELSE 'U' END,
        COALESCE([i].[Id], [d].[Id]),
        (SELECT [v].[DocumentId] FROM [app].[DocumentVersion] AS [v] WHERE [v].[Id] = COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId])),
        COALESCE([i].[DocumentVersionId], [d].[DocumentVersionId]),
        NULL,
        CASE WHEN [d].[Id] IS NULL THEN NULL ELSE (SELECT [d].[Id] AS [Id], [d].[DocumentVersionId] AS [DocumentVersionId], [d].[UserId] AS [UserId], [d].[SignedAt] AS [SignedAt], [d].[ContentHash] AS [ContentHash], [d].[WithdrawnAt] AS [WithdrawnAt], [d].[Comment] AS [Comment] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NULL THEN NULL ELSE (SELECT [i].[Id] AS [Id], [i].[DocumentVersionId] AS [DocumentVersionId], [i].[UserId] AS [UserId], [i].[SignedAt] AS [SignedAt], [i].[ContentHash] AS [ContentHash], [i].[WithdrawnAt] AS [WithdrawnAt], [i].[Comment] AS [Comment] FOR JSON PATH, WITHOUT_ARRAY_WRAPPER, INCLUDE_NULL_VALUES) END,
        CASE WHEN [i].[Id] IS NOT NULL AND [d].[Id] IS NOT NULL
             THEN NULLIF(CONCAT_WS(N',',
                   CASE WHEN [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId] THEN N'DocumentVersionId' END,
                   CASE WHEN [i].[UserId] IS DISTINCT FROM [d].[UserId] THEN N'UserId' END,
                   CASE WHEN [i].[SignedAt] IS DISTINCT FROM [d].[SignedAt] THEN N'SignedAt' END,
                   CASE WHEN [i].[ContentHash] IS DISTINCT FROM [d].[ContentHash] THEN N'ContentHash' END,
                   CASE WHEN [i].[WithdrawnAt] IS DISTINCT FROM [d].[WithdrawnAt] THEN N'WithdrawnAt' END,
                   CASE WHEN CAST([i].[Comment] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Comment] AS VARBINARY (MAX)) THEN N'Comment' END), N'')
        END,
        [ctx].[UserId], [ctx].[Source], [ctx].[DbLogin], [ctx].[AppName], [ctx].[CorrelationId], [ctx].[OperationContext], [ctx].[Ticket], [ctx].[Reason]
    FROM inserted AS [i]
    FULL OUTER JOIN deleted AS [d] ON [d].[Id] = [i].[Id]
    CROSS JOIN [audit].[fn_ChangeContext]() AS [ctx]
    WHERE [d].[Id] IS NULL OR [i].[Id] IS NULL
       OR [i].[DocumentVersionId] IS DISTINCT FROM [d].[DocumentVersionId]
           OR [i].[UserId] IS DISTINCT FROM [d].[UserId]
           OR [i].[SignedAt] IS DISTINCT FROM [d].[SignedAt]
           OR [i].[ContentHash] IS DISTINCT FROM [d].[ContentHash]
           OR [i].[WithdrawnAt] IS DISTINCT FROM [d].[WithdrawnAt]
           OR CAST([i].[Comment] AS VARBINARY (MAX)) IS DISTINCT FROM CAST([d].[Comment] AS VARBINARY (MAX))
    ;

    -- T03 §2b: advance the per-version stamp (cache key/ETag) of every version the change touches — old and new version
    -- for rows that move between versions — and record the first tampering with a Signed version.
    MERGE [app].[VersionStamp] WITH (HOLDLOCK) AS [target]
    USING (
        SELECT [x].[DocumentVersionId], MAX([l].[Id]) AS [LastChangeLogId], CAST(NULL AS DATETIME2 (7)) AS [TamperedAt]
        FROM @Logged AS [l]
        LEFT JOIN inserted AS [i] ON [i].[Id] = [l].[EntityId]
        LEFT JOIN deleted AS [d] ON [d].[Id] = [l].[EntityId]
        CROSS APPLY (VALUES ([i].[DocumentVersionId]), ([d].[DocumentVersionId])) AS [x] ([DocumentVersionId])
        JOIN [app].[DocumentVersion] AS [v] ON [v].[Id] = [x].[DocumentVersionId]
        GROUP BY [x].[DocumentVersionId]) AS [source]
    ON [target].[DocumentVersionId] = [source].[DocumentVersionId]
    WHEN MATCHED THEN
        UPDATE SET [LastChangeLogId] = CASE WHEN [source].[LastChangeLogId] > [target].[LastChangeLogId] THEN [source].[LastChangeLogId] ELSE [target].[LastChangeLogId] END,
                   [TamperedAt] = COALESCE([target].[TamperedAt], [source].[TamperedAt])
    WHEN NOT MATCHED BY TARGET THEN
        INSERT ([DocumentVersionId], [LastChangeLogId], [TamperedAt])
        VALUES ([source].[DocumentVersionId], [source].[LastChangeLogId], [source].[TamperedAt]);
END;
